-- =============================================================================
-- baasparse — PostgreSQL install schema (baseline 0001_initial)
-- =============================================================================
-- Physical realisation of docs/technical-spec/03-database-design.md, following the
-- naming standard of docs/technical-spec/02-conventions.md §2.1 and the authoritative
-- 45-table registry in §2.2 (registry actually enumerates 50 tables — all are emitted
-- below, grouped Administration / Configuration / Operational).
--
-- Properties:
--   * Idempotent: CREATE ... IF NOT EXISTS everywhere; constraints inline in CREATE
--     TABLE (so IF NOT EXISTS covers them); the one circular FK and the audit trigger
--     are added under DO-guards / DROP-IF-EXISTS. Safe to re-run.
--   * Dependency-ordered: parents before children; the single RD<->RDV cycle is closed
--     by a trailing ALTER ... ADD CONSTRAINT.
--   * Identifiers are UPPER unquoted (PostgreSQL folds them to lowercase); nothing is
--     double-quoted, so the app can reference tables case-insensitively.
--
-- Requires PostgreSQL 15+ (NULLS NOT DISTINCT unique index on OS_OPERATIONAL_STATE,
-- §3.5.22). Tested against PostgreSQL 18.
-- =============================================================================

-- SQL schema (namespace) for all engine tables. This is the schema INSIDE your
-- database (which may be named anything, e.g. baasparseDB) — TS 02 §2.1 fixes it
-- to `baasparse`. The engine's search_path must match (see --db-schema).
CREATE SCHEMA IF NOT EXISTS baasparse;
SET search_path TO baasparse, public;

-- =============================================================================
-- 3.3  ADMINISTRATION DOMAIN
-- =============================================================================

-- 3.3.1 U_USER — user accounts
CREATE TABLE IF NOT EXISTS U_USER (
  U_UID                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  U_USERNAME             TEXT        NOT NULL,
  U_DISPLAY_NAME         TEXT        NULL,
  U_EMAIL                TEXT        NULL,
  U_AUTH_SOURCE          TEXT        NOT NULL DEFAULT 'LOCAL',
  U_PASSWORD_HASH        TEXT        NULL,
  U_STATUS               TEXT        NOT NULL DEFAULT 'ACTIVE',
  U_MUST_CHANGE_PASSWORD BOOLEAN     NOT NULL DEFAULT FALSE,
  U_FAILED_LOGIN_COUNT   INT         NOT NULL DEFAULT 0,
  U_LOCKED_UNTIL         TIMESTAMPTZ NULL,
  U_PASSWORD_CHANGED_ON  TIMESTAMPTZ NULL,
  U_CREATED_BY           TEXT        NOT NULL,
  U_CREATED_ON           TIMESTAMPTZ NOT NULL DEFAULT now(),
  U_MODIFIED_BY          TEXT        NOT NULL,
  U_MODIFIED_ON          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_U_USERNAME UNIQUE (U_USERNAME),
  CONSTRAINT CK_U_STATUS CHECK (U_STATUS IN ('ACTIVE','DISABLED')),
  CONSTRAINT CK_U_AUTH_SOURCE CHECK (U_AUTH_SOURCE IN ('LOCAL','OIDC','LDAP')),
  CONSTRAINT CK_U_LOCAL_PASSWORD CHECK (U_AUTH_SOURCE <> 'LOCAL' OR U_PASSWORD_HASH IS NOT NULL)
);

-- 3.3.2 R_ROLE — roles
CREATE TABLE IF NOT EXISTS R_ROLE (
  R_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  R_NAME        TEXT        NOT NULL,
  R_DESCRIPTION TEXT        NULL,
  R_BUILT_IN    BOOLEAN     NOT NULL DEFAULT FALSE,
  R_CREATED_BY  TEXT        NOT NULL,
  R_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  R_MODIFIED_BY TEXT        NOT NULL,
  R_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_R_NAME UNIQUE (R_NAME)
);

-- 3.3.4 PRM_PERMISSION — permission catalog
CREATE TABLE IF NOT EXISTS PRM_PERMISSION (
  PRM_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PRM_CODE        TEXT        NOT NULL,
  PRM_DESCRIPTION TEXT        NULL,
  PRM_CREATED_BY  TEXT        NOT NULL,
  PRM_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRM_MODIFIED_BY TEXT        NOT NULL,
  PRM_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_PRM_CODE UNIQUE (PRM_CODE)
);

-- 3.3.3 UR_USER_ROLE — user <-> role assignment
CREATE TABLE IF NOT EXISTS UR_USER_ROLE (
  UR_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UR_U_UID       BIGINT      NOT NULL,
  UR_R_UID       BIGINT      NOT NULL,
  UR_CREATED_BY  TEXT        NOT NULL,
  UR_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UR_MODIFIED_BY TEXT        NOT NULL,
  UR_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_UR_U FOREIGN KEY (UR_U_UID) REFERENCES U_USER (U_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_UR_R FOREIGN KEY (UR_R_UID) REFERENCES R_ROLE (R_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_UR_USER_ROLE UNIQUE (UR_U_UID, UR_R_UID)
);
CREATE INDEX IF NOT EXISTS IX_UR_R ON UR_USER_ROLE (UR_R_UID);

-- 3.3.5 RP_ROLE_PERMISSION — role <-> permission grants
CREATE TABLE IF NOT EXISTS RP_ROLE_PERMISSION (
  RP_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RP_R_UID       BIGINT      NOT NULL,
  RP_PRM_UID     BIGINT      NOT NULL,
  RP_CREATED_BY  TEXT        NOT NULL,
  RP_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  RP_MODIFIED_BY TEXT        NOT NULL,
  RP_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_RP_R   FOREIGN KEY (RP_R_UID)   REFERENCES R_ROLE (R_UID)           ON DELETE RESTRICT,
  CONSTRAINT FK_RP_PRM FOREIGN KEY (RP_PRM_UID) REFERENCES PRM_PERMISSION (PRM_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_RP_ROLE_PERM UNIQUE (RP_R_UID, RP_PRM_UID)
);

-- 3.3.6 SES_SESSION — GUI sessions
CREATE TABLE IF NOT EXISTS SES_SESSION (
  SES_UID                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SES_U_UID               BIGINT      NOT NULL,
  SES_TOKEN_HASH          BYTEA       NOT NULL,
  SES_ISSUED_ON           TIMESTAMPTZ NOT NULL DEFAULT now(),
  SES_ABSOLUTE_EXPIRES_ON TIMESTAMPTZ NOT NULL,
  SES_IDLE_EXPIRES_ON     TIMESTAMPTZ NOT NULL,
  SES_LAST_SEEN_ON        TIMESTAMPTZ NOT NULL DEFAULT now(),
  SES_CLIENT_ADDR         TEXT        NULL,
  SES_REVOKED_ON          TIMESTAMPTZ NULL,
  SES_STATUS              TEXT        NOT NULL DEFAULT 'ACTIVE',
  SES_CREATED_BY          TEXT        NOT NULL,
  SES_CREATED_ON          TIMESTAMPTZ NOT NULL DEFAULT now(),
  SES_MODIFIED_BY         TEXT        NOT NULL,
  SES_MODIFIED_ON         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_SES_U FOREIGN KEY (SES_U_UID) REFERENCES U_USER (U_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_SES_TOKEN UNIQUE (SES_TOKEN_HASH),
  CONSTRAINT CK_SES_STATUS CHECK (SES_STATUS IN ('ACTIVE','EXPIRED','REVOKED'))
);
CREATE INDEX IF NOT EXISTS IX_SES_U ON SES_SESSION (SES_U_UID) WHERE SES_STATUS = 'ACTIVE';

-- 3.3.7 AT_API_TOKEN — API tokens (self-referencing rotation chain)
CREATE TABLE IF NOT EXISTS AT_API_TOKEN (
  AT_UID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AT_U_UID           BIGINT      NOT NULL,
  AT_NAME            TEXT        NOT NULL,
  AT_TOKEN_HASH      BYTEA       NOT NULL,
  AT_ISSUED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  AT_EXPIRES_ON      TIMESTAMPTZ NOT NULL,
  AT_REVOKED_ON      TIMESTAMPTZ NULL,
  AT_STATUS          TEXT        NOT NULL DEFAULT 'ACTIVE',
  AT_LAST_USED_ON    TIMESTAMPTZ NULL,
  AT_AT_UID_REPLACES BIGINT      NULL,
  AT_CREATED_BY      TEXT        NOT NULL,
  AT_CREATED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  AT_MODIFIED_BY     TEXT        NOT NULL,
  AT_MODIFIED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_AT_U           FOREIGN KEY (AT_U_UID)           REFERENCES U_USER (U_UID)       ON DELETE RESTRICT,
  CONSTRAINT FK_AT_AT_REPLACES FOREIGN KEY (AT_AT_UID_REPLACES) REFERENCES AT_API_TOKEN (AT_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_AT_TOKEN UNIQUE (AT_TOKEN_HASH),
  CONSTRAINT CK_AT_STATUS CHECK (AT_STATUS IN ('ACTIVE','REVOKED','EXPIRED'))
);
CREATE INDEX IF NOT EXISTS IX_AT_U ON AT_API_TOKEN (AT_U_UID);

-- 3.3.8 EL_EDIT_LOCK — config edit locks
CREATE TABLE IF NOT EXISTS EL_EDIT_LOCK (
  EL_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EL_ITEM_KIND   TEXT        NOT NULL,
  EL_ITEM_UID    BIGINT      NOT NULL,   -- polymorphic soft ref (no FK, §3.8.4)
  EL_U_UID       BIGINT      NOT NULL,
  EL_CHANNEL     TEXT        NOT NULL DEFAULT 'GUI',
  EL_ACQUIRED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  EL_EXPIRES_ON  TIMESTAMPTZ NOT NULL,
  EL_STATUS      TEXT        NOT NULL DEFAULT 'HELD',
  EL_CREATED_BY  TEXT        NOT NULL,
  EL_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  EL_MODIFIED_BY TEXT        NOT NULL,
  EL_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_EL_U FOREIGN KEY (EL_U_UID) REFERENCES U_USER (U_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_EL_STATUS  CHECK (EL_STATUS IN ('HELD','RELEASED','EXPIRED')),
  CONSTRAINT CK_EL_CHANNEL CHECK (EL_CHANNEL IN ('GUI','API','IMPORT'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_EL_ITEM_HELD ON EL_EDIT_LOCK (EL_ITEM_KIND, EL_ITEM_UID)
  WHERE EL_STATUS = 'HELD';

-- =============================================================================
-- 3.4  CONFIGURATION DOMAIN  (temporal pattern §3.2)
-- =============================================================================

-- 3.4.5a PL_PIPELINE — pipeline logical identity
CREATE TABLE IF NOT EXISTS PL_PIPELINE (
  PL_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PL_NAME        TEXT        NOT NULL,
  PL_DESCRIPTION TEXT        NULL,
  PL_STATUS      TEXT        NOT NULL DEFAULT 'ACTIVE',
  PL_CREATED_BY  TEXT        NOT NULL,
  PL_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PL_MODIFIED_BY TEXT        NOT NULL,
  PL_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_PL_NAME UNIQUE (PL_NAME),
  CONSTRAINT CK_PL_STATUS CHECK (PL_STATUS IN ('ACTIVE','RETIRED'))
);

-- 3.4.4 FD_FORMAT_DEFINITION — format definitions
CREATE TABLE IF NOT EXISTS FD_FORMAT_DEFINITION (
  FD_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FD_FD_UID_ROOT    BIGINT      NULL,
  FD_VERSION_NO     INT         NOT NULL,
  FD_STATUS         TEXT        NOT NULL DEFAULT 'DRAFT',
  FD_EFFECTIVE_FROM TIMESTAMPTZ NOT NULL,
  FD_END_DATE       TIMESTAMPTZ NULL,
  FD_NAME           TEXT        NOT NULL,
  FD_KIND           TEXT        NOT NULL,
  FD_VARIANT        TEXT        NOT NULL DEFAULT '',
  FD_SPEC           JSONB       NOT NULL,
  FD_CREATED_BY     TEXT        NOT NULL,
  FD_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  FD_MODIFIED_BY    TEXT        NOT NULL,
  FD_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_FD_FD_ROOT FOREIGN KEY (FD_FD_UID_ROOT) REFERENCES FD_FORMAT_DEFINITION (FD_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_FD_STATUS CHECK (FD_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED')),
  CONSTRAINT CK_FD_KIND   CHECK (FD_KIND IN ('ASN1','JSON','XML','DSV','FIXED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_FD_ROOT_VERSION ON FD_FORMAT_DEFINITION (COALESCE(FD_FD_UID_ROOT, FD_UID), FD_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_FD_ROOT_EFFECTIVE ON FD_FORMAT_DEFINITION (COALESCE(FD_FD_UID_ROOT, FD_UID), FD_EFFECTIVE_FROM) WHERE FD_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_FD_ROOT_OPEN ON FD_FORMAT_DEFINITION (COALESCE(FD_FD_UID_ROOT, FD_UID)) WHERE FD_STATUS = 'PUBLISHED' AND FD_END_DATE IS NULL;

-- 3.4.2 RE_REMOTE_ENDPOINT — SFTP/FTPS endpoints
CREATE TABLE IF NOT EXISTS RE_REMOTE_ENDPOINT (
  RE_UID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RE_RE_UID_ROOT      BIGINT      NULL,
  RE_VERSION_NO       INT         NOT NULL,
  RE_STATUS           TEXT        NOT NULL DEFAULT 'DRAFT',
  RE_EFFECTIVE_FROM   TIMESTAMPTZ NOT NULL,
  RE_END_DATE         TIMESTAMPTZ NULL,
  RE_NAME             TEXT        NOT NULL,
  RE_PROTOCOL         TEXT        NOT NULL,
  RE_HOST             TEXT        NOT NULL,
  RE_PORT             INT         NOT NULL,
  RE_REMOTE_PATH      TEXT        NOT NULL,
  RE_CREDENTIALS      JSONB       NOT NULL,
  RE_TRUST            JSONB       NULL,
  RE_POST_FETCH       TEXT        NOT NULL DEFAULT 'LEAVE',
  RE_REMOTE_DONE_PATH TEXT        NULL,
  RE_LIMITS           JSONB       NULL,
  RE_CREATED_BY       TEXT        NOT NULL,
  RE_CREATED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  RE_MODIFIED_BY      TEXT        NOT NULL,
  RE_MODIFIED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_RE_RE_ROOT FOREIGN KEY (RE_RE_UID_ROOT) REFERENCES RE_REMOTE_ENDPOINT (RE_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_RE_STATUS     CHECK (RE_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED')),
  CONSTRAINT CK_RE_PROTOCOL   CHECK (RE_PROTOCOL IN ('SFTP','FTPS')),
  CONSTRAINT CK_RE_POST_FETCH CHECK (RE_POST_FETCH IN ('LEAVE','DELETE','MOVE'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_RE_ROOT_VERSION ON RE_REMOTE_ENDPOINT (COALESCE(RE_RE_UID_ROOT, RE_UID), RE_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_RE_ROOT_EFFECTIVE ON RE_REMOTE_ENDPOINT (COALESCE(RE_RE_UID_ROOT, RE_UID), RE_EFFECTIVE_FROM) WHERE RE_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_RE_ROOT_OPEN ON RE_REMOTE_ENDPOINT (COALESCE(RE_RE_UID_ROOT, RE_UID)) WHERE RE_STATUS = 'PUBLISHED' AND RE_END_DATE IS NULL;

-- 3.4.3 AP_ARCHIVE_POLICY — archive policies
CREATE TABLE IF NOT EXISTS AP_ARCHIVE_POLICY (
  AP_UID                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AP_AP_UID_ROOT         BIGINT      NULL,
  AP_VERSION_NO          INT         NOT NULL,
  AP_STATUS              TEXT        NOT NULL DEFAULT 'DRAFT',
  AP_EFFECTIVE_FROM      TIMESTAMPTZ NOT NULL,
  AP_END_DATE            TIMESTAMPTZ NULL,
  AP_NAME                TEXT        NOT NULL,
  AP_AGE_DAYS            INT         NOT NULL,
  AP_COMPRESSION         TEXT        NOT NULL,
  AP_GROUPING            JSONB       NOT NULL,
  AP_NAME_TEMPLATE       TEXT        NOT NULL,
  AP_LOCAL_RETENTION     JSONB       NOT NULL,
  AP_SCHEDULE            TEXT        NOT NULL,
  AP_INCLUDE_QUARANTINED BOOLEAN     NOT NULL DEFAULT FALSE,
  AP_RE_UID              BIGINT      NOT NULL,
  AP_REMOTE_PATH         TEXT        NULL,
  AP_VERIFY_MODE         TEXT        NOT NULL DEFAULT 'READBACK',
  AP_MANIFEST            BOOLEAN     NOT NULL DEFAULT TRUE,
  AP_CREATED_BY          TEXT        NOT NULL,
  AP_CREATED_ON          TIMESTAMPTZ NOT NULL DEFAULT now(),
  AP_MODIFIED_BY         TEXT        NOT NULL,
  AP_MODIFIED_ON         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_AP_AP_ROOT FOREIGN KEY (AP_AP_UID_ROOT) REFERENCES AP_ARCHIVE_POLICY (AP_UID)  ON DELETE RESTRICT,
  CONSTRAINT FK_AP_RE      FOREIGN KEY (AP_RE_UID)      REFERENCES RE_REMOTE_ENDPOINT (RE_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_AP_STATUS      CHECK (AP_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED')),
  CONSTRAINT CK_AP_COMPRESSION CHECK (AP_COMPRESSION IN ('GZIP','ZIP','TAR_GZ')),
  CONSTRAINT CK_AP_VERIFY_MODE CHECK (AP_VERIFY_MODE IN ('SIZE','READBACK'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_AP_ROOT_VERSION ON AP_ARCHIVE_POLICY (COALESCE(AP_AP_UID_ROOT, AP_UID), AP_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_AP_ROOT_EFFECTIVE ON AP_ARCHIVE_POLICY (COALESCE(AP_AP_UID_ROOT, AP_UID), AP_EFFECTIVE_FROM) WHERE AP_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_AP_ROOT_OPEN ON AP_ARCHIVE_POLICY (COALESCE(AP_AP_UID_ROOT, AP_UID)) WHERE AP_STATUS = 'PUBLISHED' AND AP_END_DATE IS NULL;

-- 3.4.1 SRC_SOURCE — source definitions
CREATE TABLE IF NOT EXISTS SRC_SOURCE (
  SRC_UID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SRC_SRC_UID_ROOT      BIGINT      NULL,
  SRC_VERSION_NO        INT         NOT NULL,
  SRC_STATUS            TEXT        NOT NULL DEFAULT 'DRAFT',
  SRC_EFFECTIVE_FROM    TIMESTAMPTZ NOT NULL,
  SRC_END_DATE          TIMESTAMPTZ NULL,
  SRC_NAME              TEXT        NOT NULL,
  SRC_INPUT_DIRS        JSONB       NOT NULL,
  SRC_IN_PROGRESS_DIR   TEXT        NOT NULL,
  SRC_DONE_DIR          TEXT        NOT NULL,
  SRC_QUARANTINE_DIR    TEXT        NOT NULL,
  SRC_REJECTED_DIR      TEXT        NOT NULL,
  SRC_FILE_PATTERN      TEXT        NOT NULL,
  SRC_COLLECTION_POLICY JSONB       NOT NULL,
  SRC_FETCH_POLICY      JSONB       NULL,
  SRC_RE_UID            BIGINT      NULL,
  SRC_AP_UID            BIGINT      NULL,
  SRC_FD_UID            BIGINT      NOT NULL,
  SRC_PL_UID            BIGINT      NOT NULL,
  SRC_CREATED_BY        TEXT        NOT NULL,
  SRC_CREATED_ON        TIMESTAMPTZ NOT NULL DEFAULT now(),
  SRC_MODIFIED_BY       TEXT        NOT NULL,
  SRC_MODIFIED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_SRC_SRC_ROOT FOREIGN KEY (SRC_SRC_UID_ROOT) REFERENCES SRC_SOURCE (SRC_UID)          ON DELETE RESTRICT,
  CONSTRAINT FK_SRC_RE       FOREIGN KEY (SRC_RE_UID)       REFERENCES RE_REMOTE_ENDPOINT (RE_UID)   ON DELETE RESTRICT,
  CONSTRAINT FK_SRC_AP       FOREIGN KEY (SRC_AP_UID)       REFERENCES AP_ARCHIVE_POLICY (AP_UID)    ON DELETE RESTRICT,
  CONSTRAINT FK_SRC_FD       FOREIGN KEY (SRC_FD_UID)       REFERENCES FD_FORMAT_DEFINITION (FD_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_SRC_PL       FOREIGN KEY (SRC_PL_UID)       REFERENCES PL_PIPELINE (PL_UID)          ON DELETE RESTRICT,
  CONSTRAINT CK_SRC_STATUS CHECK (SRC_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_SRC_ROOT_VERSION ON SRC_SOURCE (COALESCE(SRC_SRC_UID_ROOT, SRC_UID), SRC_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_SRC_ROOT_EFFECTIVE ON SRC_SOURCE (COALESCE(SRC_SRC_UID_ROOT, SRC_UID), SRC_EFFECTIVE_FROM) WHERE SRC_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_SRC_ROOT_OPEN ON SRC_SOURCE (COALESCE(SRC_SRC_UID_ROOT, SRC_UID)) WHERE SRC_STATUS = 'PUBLISHED' AND SRC_END_DATE IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS UX_SRC_NAME_OPEN ON SRC_SOURCE (SRC_NAME) WHERE SRC_STATUS = 'PUBLISHED' AND SRC_END_DATE IS NULL;

-- 3.4.5b PLV_PIPELINE_VERSION — pipeline config versions
CREATE TABLE IF NOT EXISTS PLV_PIPELINE_VERSION (
  PLV_UID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PLV_PL_UID          BIGINT      NOT NULL,
  PLV_VERSION_NO      INT         NOT NULL,
  PLV_STATUS          TEXT        NOT NULL DEFAULT 'DRAFT',
  PLV_EFFECTIVE_FROM  TIMESTAMPTZ NULL,
  PLV_END_DATE        TIMESTAMPTZ NULL,
  PLV_MODE            TEXT        NOT NULL,
  PLV_STAGE_GRAPH     JSONB       NOT NULL,
  PLV_PUBLISHED_ON    TIMESTAMPTZ NULL,
  PLV_U_UID_SUBMITTED BIGINT      NULL,
  PLV_U_UID_APPROVED  BIGINT      NULL,
  PLV_CREATED_BY      TEXT        NOT NULL,
  PLV_CREATED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  PLV_MODIFIED_BY     TEXT        NOT NULL,
  PLV_MODIFIED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_PLV_PL          FOREIGN KEY (PLV_PL_UID)          REFERENCES PL_PIPELINE (PL_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_PLV_U_SUBMITTED FOREIGN KEY (PLV_U_UID_SUBMITTED) REFERENCES U_USER (U_UID)       ON DELETE RESTRICT,
  CONSTRAINT FK_PLV_U_APPROVED  FOREIGN KEY (PLV_U_UID_APPROVED)  REFERENCES U_USER (U_UID)       ON DELETE RESTRICT,
  CONSTRAINT UX_PLV_PL_VERSION UNIQUE (PLV_PL_UID, PLV_VERSION_NO),
  CONSTRAINT CK_PLV_STATUS CHECK (PLV_STATUS IN ('DRAFT','PENDING_APPROVAL','REJECTED','PUBLISHED','SUPERSEDED')),
  CONSTRAINT CK_PLV_MODE   CHECK (PLV_MODE IN ('STREAMING','COLLATING')),
  CONSTRAINT CK_PLV_FOUR_EYES CHECK (PLV_U_UID_APPROVED IS NULL OR PLV_U_UID_APPROVED <> PLV_U_UID_SUBMITTED)
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_PLV_PL_ACTIVE ON PLV_PIPELINE_VERSION (PLV_PL_UID)
  WHERE PLV_STATUS = 'PUBLISHED' AND PLV_END_DATE IS NULL;

-- 3.4.6 VR_VALIDATION_RULESET
CREATE TABLE IF NOT EXISTS VR_VALIDATION_RULESET (
  VR_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  VR_VR_UID_ROOT    BIGINT      NULL,
  VR_VERSION_NO     INT         NOT NULL,
  VR_STATUS         TEXT        NOT NULL DEFAULT 'DRAFT',
  VR_EFFECTIVE_FROM TIMESTAMPTZ NOT NULL,
  VR_END_DATE       TIMESTAMPTZ NULL,
  VR_NAME           TEXT        NOT NULL,
  VR_RULES          JSONB       NOT NULL,
  VR_CREATED_BY     TEXT        NOT NULL,
  VR_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  VR_MODIFIED_BY    TEXT        NOT NULL,
  VR_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_VR_VR_ROOT FOREIGN KEY (VR_VR_UID_ROOT) REFERENCES VR_VALIDATION_RULESET (VR_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_VR_STATUS CHECK (VR_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_VR_ROOT_VERSION ON VR_VALIDATION_RULESET (COALESCE(VR_VR_UID_ROOT, VR_UID), VR_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_VR_ROOT_EFFECTIVE ON VR_VALIDATION_RULESET (COALESCE(VR_VR_UID_ROOT, VR_UID), VR_EFFECTIVE_FROM) WHERE VR_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_VR_ROOT_OPEN ON VR_VALIDATION_RULESET (COALESCE(VR_VR_UID_ROOT, VR_UID)) WHERE VR_STATUS = 'PUBLISHED' AND VR_END_DATE IS NULL;

-- 3.4.6 CR_CORRELATION_RULE
CREATE TABLE IF NOT EXISTS CR_CORRELATION_RULE (
  CR_UID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CR_CR_UID_ROOT       BIGINT      NULL,
  CR_VERSION_NO        INT         NOT NULL,
  CR_STATUS            TEXT        NOT NULL DEFAULT 'DRAFT',
  CR_EFFECTIVE_FROM    TIMESTAMPTZ NOT NULL,
  CR_END_DATE          TIMESTAMPTZ NULL,
  CR_NAME              TEXT        NOT NULL,
  CR_KEY_SPEC          JSONB       NOT NULL,
  CR_COMPLETION_SPEC   JSONB       NOT NULL,
  CR_AGGREGATE_SPEC    JSONB       NULL,
  CR_INCOMPLETE_POLICY TEXT        NOT NULL DEFAULT 'SUSPEND',
  CR_LATE_POLICY       TEXT        NOT NULL DEFAULT 'DELTA',
  CR_MEMBER_RETENTION  INTERVAL    NULL,
  CR_CREATED_BY        TEXT        NOT NULL,
  CR_CREATED_ON        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CR_MODIFIED_BY       TEXT        NOT NULL,
  CR_MODIFIED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_CR_CR_ROOT FOREIGN KEY (CR_CR_UID_ROOT) REFERENCES CR_CORRELATION_RULE (CR_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_CR_STATUS            CHECK (CR_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED')),
  CONSTRAINT CK_CR_INCOMPLETE_POLICY CHECK (CR_INCOMPLETE_POLICY IN ('EMIT_PARTIAL','SUSPEND','DISCARD')),
  CONSTRAINT CK_CR_LATE_POLICY       CHECK (CR_LATE_POLICY IN ('DELTA','SUSPEND','DISCARD'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_CR_ROOT_VERSION ON CR_CORRELATION_RULE (COALESCE(CR_CR_UID_ROOT, CR_UID), CR_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_CR_ROOT_EFFECTIVE ON CR_CORRELATION_RULE (COALESCE(CR_CR_UID_ROOT, CR_UID), CR_EFFECTIVE_FROM) WHERE CR_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_CR_ROOT_OPEN ON CR_CORRELATION_RULE (COALESCE(CR_CR_UID_ROOT, CR_UID)) WHERE CR_STATUS = 'PUBLISHED' AND CR_END_DATE IS NULL;

-- 3.4.6 DR_DEDUP_RULE
CREATE TABLE IF NOT EXISTS DR_DEDUP_RULE (
  DR_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DR_DR_UID_ROOT    BIGINT      NULL,
  DR_VERSION_NO     INT         NOT NULL,
  DR_STATUS         TEXT        NOT NULL DEFAULT 'DRAFT',
  DR_EFFECTIVE_FROM TIMESTAMPTZ NOT NULL,
  DR_END_DATE       TIMESTAMPTZ NULL,
  DR_NAME           TEXT        NOT NULL,
  DR_KEY_SPEC       JSONB       NOT NULL,
  DR_RETENTION      INTERVAL    NOT NULL,
  DR_CREATED_BY     TEXT        NOT NULL,
  DR_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  DR_MODIFIED_BY    TEXT        NOT NULL,
  DR_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_DR_DR_ROOT FOREIGN KEY (DR_DR_UID_ROOT) REFERENCES DR_DEDUP_RULE (DR_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_DR_STATUS CHECK (DR_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_DR_ROOT_VERSION ON DR_DEDUP_RULE (COALESCE(DR_DR_UID_ROOT, DR_UID), DR_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_DR_ROOT_EFFECTIVE ON DR_DEDUP_RULE (COALESCE(DR_DR_UID_ROOT, DR_UID), DR_EFFECTIVE_FROM) WHERE DR_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_DR_ROOT_OPEN ON DR_DEDUP_RULE (COALESCE(DR_DR_UID_ROOT, DR_UID)) WHERE DR_STATUS = 'PUBLISHED' AND DR_END_DATE IS NULL;

-- 3.4.8a RD_REFERENCE_DATASET  (FK to RDV added after RDV exists — circular, §3.4.8)
CREATE TABLE IF NOT EXISTS RD_REFERENCE_DATASET (
  RD_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RD_NAME           TEXT        NOT NULL,
  RD_DESCRIPTION    TEXT        NULL,
  RD_KEY_SPEC       JSONB       NOT NULL,
  RD_READINESS      JSONB       NULL,
  RD_RDV_UID_ACTIVE BIGINT      NULL,
  RD_CREATED_BY     TEXT        NOT NULL,
  RD_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  RD_MODIFIED_BY    TEXT        NOT NULL,
  RD_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_RD_NAME UNIQUE (RD_NAME)
);

-- 3.4.8b RDV_REFERENCE_DATA_VERSION
CREATE TABLE IF NOT EXISTS RDV_REFERENCE_DATA_VERSION (
  RDV_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RDV_RD_UID         BIGINT      NOT NULL,
  RDV_VERSION_NO     INT         NOT NULL,
  RDV_STATUS         TEXT        NOT NULL DEFAULT 'LOADING',
  RDV_EFFECTIVE_FROM TIMESTAMPTZ NULL,
  RDV_END_DATE       TIMESTAMPTZ NULL,
  RDV_ROW_COUNT      BIGINT      NULL,
  RDV_CHECKSUM       TEXT        NULL,
  RDV_SOURCE_REF     TEXT        NULL,
  RDV_LOADED_ON      TIMESTAMPTZ NULL,
  RDV_CREATED_BY     TEXT        NOT NULL,
  RDV_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  RDV_MODIFIED_BY    TEXT        NOT NULL,
  RDV_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_RDV_RD FOREIGN KEY (RDV_RD_UID) REFERENCES RD_REFERENCE_DATASET (RD_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_RDV_RD_VERSION UNIQUE (RDV_RD_UID, RDV_VERSION_NO),
  CONSTRAINT CK_RDV_STATUS CHECK (RDV_STATUS IN ('LOADING','READY','ACTIVE','RETIRED','FAILED'))
);

-- 3.4.8b close the RD <-> RDV cycle (idempotent add)
DO $$ BEGIN
  ALTER TABLE RD_REFERENCE_DATASET
    ADD CONSTRAINT FK_RD_RDV_ACTIVE FOREIGN KEY (RD_RDV_UID_ACTIVE)
    REFERENCES RDV_REFERENCE_DATA_VERSION (RDV_UID) ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 3.4.8c RDR_REFERENCE_DATA_ROW  (LIST partitioned, one partition per dataset version)
CREATE TABLE IF NOT EXISTS RDR_REFERENCE_DATA_ROW (
  RDR_UID            BIGINT GENERATED ALWAYS AS IDENTITY,
  RDR_RDV_UID        BIGINT      NOT NULL,
  RDR_KEY            TEXT        NOT NULL,
  RDR_KEY_TO         TEXT        NULL,
  RDR_ATTRS          JSONB       NOT NULL,
  RDR_EFFECTIVE_FROM TIMESTAMPTZ NULL,
  RDR_END_DATE       TIMESTAMPTZ NULL,
  RDR_CREATED_BY     TEXT        NOT NULL,
  RDR_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  RDR_MODIFIED_BY    TEXT        NOT NULL,
  RDR_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT PK_RDR PRIMARY KEY (RDR_UID, RDR_RDV_UID),
  CONSTRAINT FK_RDR_RDV FOREIGN KEY (RDR_RDV_UID) REFERENCES RDV_REFERENCE_DATA_VERSION (RDV_UID) ON DELETE RESTRICT
) PARTITION BY LIST (RDR_RDV_UID);
-- default partition so plain inserts work before per-version partitions are provisioned
CREATE TABLE IF NOT EXISTS RDR_REFERENCE_DATA_ROW_DEFAULT PARTITION OF RDR_REFERENCE_DATA_ROW DEFAULT;
CREATE INDEX IF NOT EXISTS IX_RDR_DEFAULT_KEY ON RDR_REFERENCE_DATA_ROW_DEFAULT (RDR_KEY, RDR_EFFECTIVE_FROM);

-- 3.4.6 ER_ENRICHMENT_RULE  (references RD)
CREATE TABLE IF NOT EXISTS ER_ENRICHMENT_RULE (
  ER_UID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ER_ER_UID_ROOT     BIGINT      NULL,
  ER_VERSION_NO      INT         NOT NULL,
  ER_STATUS          TEXT        NOT NULL DEFAULT 'DRAFT',
  ER_EFFECTIVE_FROM  TIMESTAMPTZ NOT NULL,
  ER_END_DATE        TIMESTAMPTZ NULL,
  ER_NAME            TEXT        NOT NULL,
  ER_RD_UID          BIGINT      NOT NULL,
  ER_LOOKUP_SPEC     JSONB       NOT NULL,
  ER_ON_MISS         TEXT        NOT NULL DEFAULT 'BLANK',
  ER_DEFAULT_VALUE   JSONB       NULL,
  ER_EFFECTIVE_DATED BOOLEAN     NOT NULL DEFAULT FALSE,
  ER_CREATED_BY      TEXT        NOT NULL,
  ER_CREATED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  ER_MODIFIED_BY     TEXT        NOT NULL,
  ER_MODIFIED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_ER_ER_ROOT FOREIGN KEY (ER_ER_UID_ROOT) REFERENCES ER_ENRICHMENT_RULE (ER_UID)   ON DELETE RESTRICT,
  CONSTRAINT FK_ER_RD      FOREIGN KEY (ER_RD_UID)      REFERENCES RD_REFERENCE_DATASET (RD_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_ER_STATUS  CHECK (ER_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED')),
  CONSTRAINT CK_ER_ON_MISS CHECK (ER_ON_MISS IN ('BLANK','DEFAULT','SUSPEND'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_ER_ROOT_VERSION ON ER_ENRICHMENT_RULE (COALESCE(ER_ER_UID_ROOT, ER_UID), ER_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_ER_ROOT_EFFECTIVE ON ER_ENRICHMENT_RULE (COALESCE(ER_ER_UID_ROOT, ER_UID), ER_EFFECTIVE_FROM) WHERE ER_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_ER_ROOT_OPEN ON ER_ENRICHMENT_RULE (COALESCE(ER_ER_UID_ROOT, ER_UID)) WHERE ER_STATUS = 'PUBLISHED' AND ER_END_DATE IS NULL;

-- 3.4.6 TR_TRANSFORM_RULESET
CREATE TABLE IF NOT EXISTS TR_TRANSFORM_RULESET (
  TR_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TR_TR_UID_ROOT    BIGINT      NULL,
  TR_VERSION_NO     INT         NOT NULL,
  TR_STATUS         TEXT        NOT NULL DEFAULT 'DRAFT',
  TR_EFFECTIVE_FROM TIMESTAMPTZ NOT NULL,
  TR_END_DATE       TIMESTAMPTZ NULL,
  TR_NAME           TEXT        NOT NULL,
  TR_RULES          JSONB       NOT NULL,
  TR_OUTPUT_SCHEMA  JSONB       NULL,
  TR_CREATED_BY     TEXT        NOT NULL,
  TR_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  TR_MODIFIED_BY    TEXT        NOT NULL,
  TR_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_TR_TR_ROOT FOREIGN KEY (TR_TR_UID_ROOT) REFERENCES TR_TRANSFORM_RULESET (TR_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_TR_STATUS CHECK (TR_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_TR_ROOT_VERSION ON TR_TRANSFORM_RULESET (COALESCE(TR_TR_UID_ROOT, TR_UID), TR_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_TR_ROOT_EFFECTIVE ON TR_TRANSFORM_RULESET (COALESCE(TR_TR_UID_ROOT, TR_UID), TR_EFFECTIVE_FROM) WHERE TR_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_TR_ROOT_OPEN ON TR_TRANSFORM_RULESET (COALESCE(TR_TR_UID_ROOT, TR_UID)) WHERE TR_STATUS = 'PUBLISHED' AND TR_END_DATE IS NULL;

-- 3.4.7 DS_DESTINATION
CREATE TABLE IF NOT EXISTS DS_DESTINATION (
  DS_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DS_DS_UID_ROOT    BIGINT      NULL,
  DS_VERSION_NO     INT         NOT NULL,
  DS_STATUS         TEXT        NOT NULL DEFAULT 'DRAFT',
  DS_EFFECTIVE_FROM TIMESTAMPTZ NOT NULL,
  DS_END_DATE       TIMESTAMPTZ NULL,
  DS_NAME           TEXT        NOT NULL,
  DS_KIND           TEXT        NOT NULL,
  DS_SPEC           JSONB       NOT NULL,
  DS_ROUTING        JSONB       NULL,
  DS_SPOOL_POLICY   JSONB       NOT NULL,
  DS_CALLBACK       JSONB       NULL,
  DS_RETENTION      JSONB       NOT NULL,
  DS_CREATED_BY     TEXT        NOT NULL,
  DS_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  DS_MODIFIED_BY    TEXT        NOT NULL,
  DS_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_DS_DS_ROOT FOREIGN KEY (DS_DS_UID_ROOT) REFERENCES DS_DESTINATION (DS_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_DS_STATUS CHECK (DS_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED')),
  CONSTRAINT CK_DS_KIND   CHECK (DS_KIND IN ('FILE','RDBMS'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_DS_ROOT_VERSION ON DS_DESTINATION (COALESCE(DS_DS_UID_ROOT, DS_UID), DS_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_DS_ROOT_EFFECTIVE ON DS_DESTINATION (COALESCE(DS_DS_UID_ROOT, DS_UID), DS_EFFECTIVE_FROM) WHERE DS_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_DS_ROOT_OPEN ON DS_DESTINATION (COALESCE(DS_DS_UID_ROOT, DS_UID)) WHERE DS_STATUS = 'PUBLISHED' AND DS_END_DATE IS NULL;

-- 3.4.9 CG_CORRELATION_GROUP  (v2 seam; shipped, unused in v1)
CREATE TABLE IF NOT EXISTS CG_CORRELATION_GROUP (
  CG_UID             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CG_CG_UID_ROOT     BIGINT      NULL,
  CG_VERSION_NO      INT         NOT NULL,
  CG_STATUS          TEXT        NOT NULL DEFAULT 'DRAFT',
  CG_EFFECTIVE_FROM  TIMESTAMPTZ NOT NULL,
  CG_END_DATE        TIMESTAMPTZ NULL,
  CG_NAME            TEXT        NOT NULL,
  CG_KEY_SPEC        JSONB       NOT NULL,
  CG_PIPELINES       JSONB       NOT NULL,
  CG_COMPLETION_SPEC JSONB       NOT NULL,
  CG_CREATED_BY      TEXT        NOT NULL,
  CG_CREATED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CG_MODIFIED_BY     TEXT        NOT NULL,
  CG_MODIFIED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_CG_CG_ROOT FOREIGN KEY (CG_CG_UID_ROOT) REFERENCES CG_CORRELATION_GROUP (CG_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_CG_STATUS CHECK (CG_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_CG_ROOT_VERSION ON CG_CORRELATION_GROUP (COALESCE(CG_CG_UID_ROOT, CG_UID), CG_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_CG_ROOT_EFFECTIVE ON CG_CORRELATION_GROUP (COALESCE(CG_CG_UID_ROOT, CG_UID), CG_EFFECTIVE_FROM) WHERE CG_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_CG_ROOT_OPEN ON CG_CORRELATION_GROUP (COALESCE(CG_CG_UID_ROOT, CG_UID)) WHERE CG_STATUS = 'PUBLISHED' AND CG_END_DATE IS NULL;

-- =============================================================================
-- 3.5  OPERATIONAL DOMAIN
-- =============================================================================

-- 3.5.18 INS_INSTANCE — instance registry
CREATE TABLE IF NOT EXISTS INS_INSTANCE (
  INS_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  INS_NAME           TEXT        NOT NULL,
  INS_HOST           TEXT        NOT NULL,
  INS_ENGINE_VERSION TEXT        NOT NULL,
  INS_STATUS         TEXT        NOT NULL DEFAULT 'STARTING',
  INS_STARTED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  INS_HEARTBEAT_ON   TIMESTAMPTZ NOT NULL DEFAULT now(),
  INS_MGMT_ADDR      TEXT        NULL,
  INS_CREATED_BY     TEXT        NOT NULL,
  INS_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  INS_MODIFIED_BY    TEXT        NOT NULL,
  INS_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_INS_NAME UNIQUE (INS_NAME),
  CONSTRAINT CK_INS_STATUS CHECK (INS_STATUS IN ('STARTING','READY','DEGRADED','DRAINING','STOPPED'))
);

-- 3.5.14 SQ_SEQUENCE_ALLOCATOR — named transactional counters
CREATE TABLE IF NOT EXISTS SQ_SEQUENCE_ALLOCATOR (
  SQ_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SQ_NAME        TEXT        NOT NULL,
  SQ_LAST_VALUE  BIGINT      NOT NULL DEFAULT 0,
  SQ_CHAIN_HASH  BYTEA       NULL,
  SQ_CHAIN_ON    TIMESTAMPTZ NULL,
  SQ_CREATED_BY  TEXT        NOT NULL,
  SQ_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  SQ_MODIFIED_BY TEXT        NOT NULL,
  SQ_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_SQ_NAME UNIQUE (SQ_NAME)
);

-- 3.5.21 SM_SCHEMA_MIGRATION — migration ledger
CREATE TABLE IF NOT EXISTS SM_SCHEMA_MIGRATION (
  SM_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SM_VERSION     TEXT        NOT NULL,
  SM_CHECKSUM    TEXT        NOT NULL,
  SM_STATUS      TEXT        NOT NULL DEFAULT 'APPLIED',
  SM_APPLIED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  SM_DURATION_MS BIGINT      NULL,
  SM_CREATED_BY  TEXT        NOT NULL,
  SM_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  SM_MODIFIED_BY TEXT        NOT NULL,
  SM_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_SM_VERSION UNIQUE (SM_VERSION),
  CONSTRAINT CK_SM_STATUS CHECK (SM_STATUS IN ('APPLIED','FAILED'))
);

-- 3.5.20 TM_TOKEN_MAP — deterministic PII token map
CREATE TABLE IF NOT EXISTS TM_TOKEN_MAP (
  TM_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TM_KIND           TEXT        NOT NULL,
  TM_TOKEN          TEXT        NOT NULL,
  TM_IDENTIFIER_ENC BYTEA       NOT NULL,
  TM_KEY_VER        INT         NOT NULL DEFAULT 1,
  TM_CREATED_BY     TEXT        NOT NULL,
  TM_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  TM_MODIFIED_BY    TEXT        NOT NULL,
  TM_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT UX_TM_KIND_TOKEN UNIQUE (TM_KIND, TM_TOKEN),
  CONSTRAINT CK_TM_KIND CHECK (TM_KIND IN ('MSISDN','IMSI','IMEI','OTHER'))
);

-- 3.5.3 FR_FETCH_REGISTRY — already-fetched guard
CREATE TABLE IF NOT EXISTS FR_FETCH_REGISTRY (
  FR_UID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FR_RE_UID        BIGINT      NOT NULL,
  FR_SRC_UID       BIGINT      NULL,
  FR_REMOTE_NAME   TEXT        NOT NULL,
  FR_SIZE_BYTES    BIGINT      NULL,
  FR_CHECKSUM      TEXT        NOT NULL,
  FR_STATUS        TEXT        NOT NULL DEFAULT 'DOWNLOADED',
  FR_REMOTE_ACTION TEXT        NULL,
  FR_FETCHED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  FR_LOCAL_NAME    TEXT        NULL,
  FR_CREATED_BY    TEXT        NOT NULL,
  FR_CREATED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  FR_MODIFIED_BY   TEXT        NOT NULL,
  FR_MODIFIED_ON   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_FR_RE  FOREIGN KEY (FR_RE_UID)  REFERENCES RE_REMOTE_ENDPOINT (RE_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_FR_SRC FOREIGN KEY (FR_SRC_UID) REFERENCES SRC_SOURCE (SRC_UID)        ON DELETE RESTRICT,
  CONSTRAINT UX_FR_RE_NAME UNIQUE (FR_RE_UID, FR_REMOTE_NAME, FR_CHECKSUM),
  CONSTRAINT CK_FR_STATUS CHECK (FR_STATUS IN ('DOWNLOADED','PLACED','SKIPPED','FAILED')),
  CONSTRAINT CK_FR_REMOTE_ACTION CHECK (FR_REMOTE_ACTION IS NULL OR FR_REMOTE_ACTION IN ('PENDING','OK','FAILED'))
);

-- 3.5.1 PF_PROCESSED_FILE — processed-file record
CREATE TABLE IF NOT EXISTS PF_PROCESSED_FILE (
  PF_UID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PF_FILE_UID          BIGINT      NOT NULL,
  PF_SRC_UID           BIGINT      NOT NULL,
  PF_PLV_UID           BIGINT      NOT NULL,
  PF_NAME              TEXT        NOT NULL,
  PF_PATH              TEXT        NOT NULL,
  PF_SIZE_BYTES        BIGINT      NOT NULL,
  PF_CHECKSUM          TEXT        NULL,
  PF_CHECKSUM_ALGO     TEXT        NOT NULL DEFAULT 'SHA256',
  PF_SEQUENCE_NO       BIGINT      NULL,
  PF_STATUS            TEXT        NOT NULL DEFAULT 'COLLECTED',
  PF_RECON_STATE       TEXT        NOT NULL DEFAULT 'PENDING',
  PF_DECLARED_COUNT    BIGINT      NULL,
  PF_RECORD_COUNT      BIGINT      NULL,
  PF_ATTEMPT_COUNT     INT         NOT NULL DEFAULT 0,
  PF_COMPLETION_MARKER TEXT        NULL,
  PF_INS_UID           BIGINT      NULL,
  PF_FR_UID            BIGINT      NULL,
  PF_COLLECTED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  PF_STARTED_ON        TIMESTAMPTZ NULL,
  PF_COMPLETED_ON      TIMESTAMPTZ NULL,
  PF_CREATED_BY        TEXT        NOT NULL,
  PF_CREATED_ON        TIMESTAMPTZ NOT NULL DEFAULT now(),
  PF_MODIFIED_BY       TEXT        NOT NULL,
  PF_MODIFIED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_PF_SRC FOREIGN KEY (PF_SRC_UID) REFERENCES SRC_SOURCE (SRC_UID)           ON DELETE RESTRICT,
  CONSTRAINT FK_PF_PLV FOREIGN KEY (PF_PLV_UID) REFERENCES PLV_PIPELINE_VERSION (PLV_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_PF_INS FOREIGN KEY (PF_INS_UID) REFERENCES INS_INSTANCE (INS_UID)         ON DELETE RESTRICT,
  CONSTRAINT FK_PF_FR  FOREIGN KEY (PF_FR_UID)  REFERENCES FR_FETCH_REGISTRY (FR_UID)     ON DELETE RESTRICT,
  CONSTRAINT UX_PF_FILE_UID UNIQUE (PF_FILE_UID),
  CONSTRAINT CK_PF_STATUS CHECK (PF_STATUS IN
    ('COLLECTED','IN_PROGRESS','DONE','SUSPENDED','QUARANTINED','REJECTED_DUPLICATE','ARCHIVED','MISSING_ON_DISK')),
  CONSTRAINT CK_PF_RECON_STATE CHECK (PF_RECON_STATE IN ('PENDING','BALANCED','EXCEPTION','INDETERMINATE_COUNT'))
);
CREATE INDEX IF NOT EXISTS IX_PF_SRC_NAME     ON PF_PROCESSED_FILE (PF_SRC_UID, PF_NAME);
CREATE INDEX IF NOT EXISTS IX_PF_SRC_CHECKSUM ON PF_PROCESSED_FILE (PF_SRC_UID, PF_CHECKSUM);
CREATE INDEX IF NOT EXISTS IX_PF_SRC_SEQ      ON PF_PROCESSED_FILE (PF_SRC_UID, PF_SEQUENCE_NO) WHERE PF_SEQUENCE_NO IS NOT NULL;
CREATE INDEX IF NOT EXISTS IX_PF_STATUS       ON PF_PROCESSED_FILE (PF_STATUS, PF_SRC_UID) WHERE PF_STATUS NOT IN ('DONE','REJECTED_DUPLICATE','ARCHIVED');
CREATE INDEX IF NOT EXISTS IX_PF_COLLECTED_ON ON PF_PROCESSED_FILE (PF_COLLECTED_ON);
-- Exactly-once backstop (BR-COL-006, BR-HA-004): at most one DONE processed-file
-- per source+name. Makes the database the arbiter of the claim/re-arrival race —
-- a duplicate completion fails with 23505 instead of silently inserting a second
-- DONE row. (Replay/re-send, when added, will bypass via dedup-override semantics.)
CREATE UNIQUE INDEX IF NOT EXISTS UX_PF_SRC_NAME_DONE ON PF_PROCESSED_FILE (PF_SRC_UID, PF_NAME) WHERE PF_STATUS = 'DONE';

-- 3.5.2 FC_FILE_CLAIM — distributed claim/lease + checkpoint
CREATE TABLE IF NOT EXISTS FC_FILE_CLAIM (
  FC_UID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FC_SRC_UID           BIGINT      NOT NULL,
  FC_FILE_NAME         TEXT        NOT NULL,
  FC_PF_UID            BIGINT      NULL,
  FC_INS_UID           BIGINT      NOT NULL,
  FC_STATUS            TEXT        NOT NULL DEFAULT 'HELD',
  FC_FENCE             BIGINT      NOT NULL DEFAULT 1,
  FC_PATH              TEXT        NOT NULL DEFAULT 'INPUT',
  FC_ACQUIRED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  FC_EXPIRES_ON        TIMESTAMPTZ NOT NULL,
  FC_HEARTBEAT_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  FC_ATTEMPT           INT         NOT NULL DEFAULT 1,
  FC_CHECKPOINT_OFFSET BIGINT      NOT NULL DEFAULT 0,
  FC_CHECKPOINT_RECORD BIGINT      NOT NULL DEFAULT 0,
  FC_CHECKPOINT        JSONB       NULL,
  FC_CHECKPOINT_ON     TIMESTAMPTZ NULL,
  FC_CHECKPOINT_PREV   JSONB       NULL,
  FC_STALL_COUNT       INT         NOT NULL DEFAULT 0,
  FC_CREATED_BY        TEXT        NOT NULL,
  FC_CREATED_ON        TIMESTAMPTZ NOT NULL DEFAULT now(),
  FC_MODIFIED_BY       TEXT        NOT NULL,
  FC_MODIFIED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_FC_SRC FOREIGN KEY (FC_SRC_UID) REFERENCES SRC_SOURCE (SRC_UID)       ON DELETE RESTRICT,
  CONSTRAINT FK_FC_PF  FOREIGN KEY (FC_PF_UID)  REFERENCES PF_PROCESSED_FILE (PF_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_FC_INS FOREIGN KEY (FC_INS_UID) REFERENCES INS_INSTANCE (INS_UID)     ON DELETE RESTRICT,
  CONSTRAINT UX_FC_PF UNIQUE (FC_PF_UID),
  CONSTRAINT CK_FC_STATUS CHECK (FC_STATUS IN ('HELD','RELEASED')),
  CONSTRAINT CK_FC_PATH   CHECK (FC_PATH IN ('INPUT','IN_PROGRESS'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_FC_SRC_NAME_HELD ON FC_FILE_CLAIM (FC_SRC_UID, FC_FILE_NAME) WHERE FC_STATUS = 'HELD';
CREATE INDEX IF NOT EXISTS IX_FC_EXPIRES  ON FC_FILE_CLAIM (FC_EXPIRES_ON) WHERE FC_STATUS = 'HELD';
CREATE INDEX IF NOT EXISTS IX_FC_RELEASED ON FC_FILE_CLAIM (FC_PF_UID) WHERE FC_STATUS = 'RELEASED';

-- 3.5.4 DK_DEDUP_KEY — dedup key store (RANGE partitioned by event date)
CREATE TABLE IF NOT EXISTS DK_DEDUP_KEY (
  DK_UID          BIGINT GENERATED ALWAYS AS IDENTITY,
  DK_PL_UID       BIGINT      NOT NULL,
  DK_KEY_HASH     BYTEA       NOT NULL,
  DK_KEY_DATE     DATE        NOT NULL,
  DK_PF_UID       BIGINT      NOT NULL,
  DK_RECORD_INDEX BIGINT      NOT NULL,
  DK_CREATED_BY   TEXT        NOT NULL,
  DK_CREATED_ON   TIMESTAMPTZ NOT NULL DEFAULT now(),
  DK_MODIFIED_BY  TEXT        NOT NULL,
  DK_MODIFIED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT PK_DK PRIMARY KEY (DK_UID, DK_KEY_DATE),
  CONSTRAINT FK_DK_PL FOREIGN KEY (DK_PL_UID) REFERENCES PL_PIPELINE (PL_UID)       ON DELETE RESTRICT,
  CONSTRAINT FK_DK_PF FOREIGN KEY (DK_PF_UID) REFERENCES PF_PROCESSED_FILE (PF_UID) ON DELETE RESTRICT
) PARTITION BY RANGE (DK_KEY_DATE);
CREATE UNIQUE INDEX IF NOT EXISTS UX_DK_SCOPE_KEY ON DK_DEDUP_KEY (DK_PL_UID, DK_KEY_HASH, DK_KEY_DATE);
-- default partition so plain inserts work before the PARTITION_MAINTAIN job provisions daily partitions
CREATE TABLE IF NOT EXISTS DK_DEDUP_KEY_DEFAULT PARTITION OF DK_DEDUP_KEY DEFAULT;

-- 3.5.5 CW_COLLATION_WINDOW — open collation windows (HASH partitioned, 16-way)
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW (
  CW_UID             BIGINT GENERATED ALWAYS AS IDENTITY,
  CW_KEY_HASH        BIGINT      NOT NULL,
  CW_PL_UID          BIGINT      NOT NULL,
  CW_PLV_UID         BIGINT      NOT NULL,
  CW_CR_UID          BIGINT      NOT NULL,
  CW_KEY             TEXT        NOT NULL,
  CW_KEY_GEN         INT         NOT NULL DEFAULT 1,
  CW_WINDOW_START    TIMESTAMPTZ NOT NULL,
  CW_WINDOW_END      TIMESTAMPTZ NULL,
  CW_STATUS          TEXT        NOT NULL DEFAULT 'OPEN',
  CW_TRIGGER_STATE   JSONB       NULL,
  CW_DEADLINE_ON     TIMESTAMPTZ NULL,
  CW_DUE_REASON      TEXT        NULL,
  CW_MEMBER_COUNT    INT         NOT NULL DEFAULT 0,
  CW_CONTRIB_FILES   JSONB       NULL,
  CW_AGG_STATE       JSONB       NULL,
  CW_OUTPUT_IDENTITY TEXT        NULL,
  CW_ADJUSTMENT_SEQ  INT         NOT NULL DEFAULT 0,
  CW_EMITTED_BODY    JSONB       NULL,
  CW_INS_UID         BIGINT      NULL,
  CW_EMIT_EXPIRES_ON TIMESTAMPTZ NULL,
  CW_OPENED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CW_LAST_APPEND_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CW_EMITTED_ON      TIMESTAMPTZ NULL,
  CW_CREATED_BY      TEXT        NOT NULL,
  CW_CREATED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CW_MODIFIED_BY     TEXT        NOT NULL,
  CW_MODIFIED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT PK_CW PRIMARY KEY (CW_UID, CW_KEY_HASH),
  CONSTRAINT FK_CW_PL  FOREIGN KEY (CW_PL_UID)  REFERENCES PL_PIPELINE (PL_UID)           ON DELETE RESTRICT,
  CONSTRAINT FK_CW_PLV FOREIGN KEY (CW_PLV_UID) REFERENCES PLV_PIPELINE_VERSION (PLV_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_CW_CR  FOREIGN KEY (CW_CR_UID)  REFERENCES CR_CORRELATION_RULE (CR_UID)   ON DELETE RESTRICT,
  CONSTRAINT FK_CW_INS FOREIGN KEY (CW_INS_UID) REFERENCES INS_INSTANCE (INS_UID)         ON DELETE RESTRICT,
  CONSTRAINT CK_CW_STATUS CHECK (CW_STATUS IN ('OPEN','EMITTING','EMITTED','SUSPENDED','DISCARDED')),
  CONSTRAINT CK_CW_DUE_REASON CHECK (CW_DUE_REASON IS NULL OR CW_DUE_REASON IN ('GRACE','END_SIGNAL','COUNT','SESSION_CLOSE','FLUSH'))
) PARTITION BY HASH (CW_KEY_HASH);
CREATE UNIQUE INDEX IF NOT EXISTS UX_CW_LIVE ON CW_COLLATION_WINDOW (CW_PL_UID, CW_KEY_HASH, CW_KEY_GEN, CW_KEY, CW_WINDOW_START);
CREATE INDEX IF NOT EXISTS IX_CW_DUE       ON CW_COLLATION_WINDOW (CW_DEADLINE_ON) WHERE CW_STATUS = 'OPEN';
CREATE INDEX IF NOT EXISTS IX_CW_EMITTING  ON CW_COLLATION_WINDOW (CW_EMIT_EXPIRES_ON) WHERE CW_STATUS = 'EMITTING';
CREATE INDEX IF NOT EXISTS IX_CW_PL_STATUS ON CW_COLLATION_WINDOW (CW_PL_UID, CW_STATUS);
-- 16 fixed hash partitions (§3.6.3)
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H00 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H01 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H02 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H03 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H04 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H05 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H06 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H07 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H08 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H09 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H10 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H11 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H12 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H13 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H14 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS CW_COLLATION_WINDOW_H15 PARTITION OF CW_COLLATION_WINDOW FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- 3.5.6 CM_COLLATION_MEMBER — window members (HASH partitioned, co-aligned with CW)
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER (
  CM_UID          BIGINT GENERATED ALWAYS AS IDENTITY,
  CM_KEY_HASH     BIGINT      NOT NULL,
  CM_CW_UID       BIGINT      NOT NULL,
  CM_PF_UID       BIGINT      NOT NULL,
  CM_RECORD_INDEX BIGINT      NOT NULL,
  CM_EVENT_TIME   TIMESTAMPTZ NOT NULL,
  CM_STATUS       TEXT        NOT NULL DEFAULT 'OPEN',
  CM_BODY         JSONB       NULL,
  CM_CREATED_BY   TEXT        NOT NULL,
  CM_CREATED_ON   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CM_MODIFIED_BY  TEXT        NOT NULL,
  CM_MODIFIED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT PK_CM PRIMARY KEY (CM_UID, CM_KEY_HASH),
  CONSTRAINT FK_CM_CW FOREIGN KEY (CM_CW_UID, CM_KEY_HASH) REFERENCES CW_COLLATION_WINDOW (CW_UID, CW_KEY_HASH) ON DELETE RESTRICT,
  CONSTRAINT FK_CM_PF FOREIGN KEY (CM_PF_UID) REFERENCES PF_PROCESSED_FILE (PF_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_CM_STATUS CHECK (CM_STATUS IN ('OPEN','CONSUMED'))
) PARTITION BY HASH (CM_KEY_HASH);
CREATE UNIQUE INDEX IF NOT EXISTS UX_CM_MEMBER ON CM_COLLATION_MEMBER (CM_CW_UID, CM_PF_UID, CM_RECORD_INDEX, CM_KEY_HASH);
CREATE INDEX IF NOT EXISTS IX_CM_PF ON CM_COLLATION_MEMBER (CM_PF_UID);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H00 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H01 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H02 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H03 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H04 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H05 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H06 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H07 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H08 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H09 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H10 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H11 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H12 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H13 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H14 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS CM_COLLATION_MEMBER_H15 PARTITION OF CM_COLLATION_MEMBER FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- 3.5.8 SE_SUSPENSE_ESCROW — bounded per-record escrow (optional)
CREATE TABLE IF NOT EXISTS SE_SUSPENSE_ESCROW (
  SE_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SE_BODY        BYTEA       NOT NULL,
  SE_SIZE_BYTES  INT         NOT NULL,
  SE_SHA256      TEXT        NULL,
  SE_ENCODING    JSONB       NULL,
  SE_EXPIRES_ON  TIMESTAMPTZ NOT NULL,
  SE_CREATED_BY  TEXT        NOT NULL,
  SE_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  SE_MODIFIED_BY TEXT        NOT NULL,
  SE_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT CK_SE_SIZE CHECK (SE_SIZE_BYTES = octet_length(SE_BODY) AND SE_SIZE_BYTES <= 1048576)
);
CREATE INDEX IF NOT EXISTS IX_SE_EXPIRES ON SE_SUSPENSE_ESCROW (SE_EXPIRES_ON);

-- 3.5.24 RQ_REPROCESS_REQUEST — audited reprocess/replay/re-send (before SU: SU references RQ)
CREATE TABLE IF NOT EXISTS RQ_REPROCESS_REQUEST (
  RQ_UID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RQ_KIND         TEXT        NOT NULL,
  RQ_STATUS       TEXT        NOT NULL DEFAULT 'SUBMITTED',
  RQ_PARAMS       JSONB       NOT NULL,
  RQ_U_UID        BIGINT      NOT NULL,
  RQ_ITEM_COUNT   BIGINT      NOT NULL DEFAULT 0,
  RQ_DONE_COUNT   BIGINT      NOT NULL DEFAULT 0,
  RQ_FAILED_COUNT BIGINT      NOT NULL DEFAULT 0,
  RQ_RESULT       JSONB       NULL,
  RQ_STARTED_ON   TIMESTAMPTZ NULL,
  RQ_FINISHED_ON  TIMESTAMPTZ NULL,
  RQ_CREATED_BY   TEXT        NOT NULL,
  RQ_CREATED_ON   TIMESTAMPTZ NOT NULL DEFAULT now(),
  RQ_MODIFIED_BY  TEXT        NOT NULL,
  RQ_MODIFIED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_RQ_U FOREIGN KEY (RQ_U_UID) REFERENCES U_USER (U_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_RQ_KIND   CHECK (RQ_KIND IN ('REPROCESS','REPLAY','RESEND')),
  CONSTRAINT CK_RQ_STATUS CHECK (RQ_STATUS IN ('SUBMITTED','RUNNING','COMPLETED','PARTIAL','FAILED','CANCELLED'))
);
CREATE INDEX IF NOT EXISTS IX_RQ_STATUS ON RQ_REPROCESS_REQUEST (RQ_STATUS, RQ_CREATED_ON) WHERE RQ_STATUS IN ('SUBMITTED','RUNNING');

-- 3.5.7 SU_SUSPENSE — suspense entries
CREATE TABLE IF NOT EXISTS SU_SUSPENSE (
  SU_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SU_PF_UID         BIGINT      NULL,
  SU_CW_UID         BIGINT      NULL,
  SU_CW_KEY_HASH    BIGINT      NULL,
  SU_SRC_UID        BIGINT      NOT NULL,
  SU_SCOPE          TEXT        NOT NULL DEFAULT 'RECORD',
  SU_RECORD_INDEX   BIGINT      NULL,
  SU_BYTE_OFFSET    BIGINT      NULL,
  SU_BYTE_LENGTH    BIGINT      NULL,
  SU_STAGE          TEXT        NOT NULL,
  SU_REASON_CODE    TEXT        NOT NULL,
  SU_REASON_CLASS   TEXT        NOT NULL DEFAULT 'PERMANENT',
  SU_REASON_DETAIL  JSONB       NULL,
  SU_PLV_UID        BIGINT      NULL,
  SU_STATUS         TEXT        NOT NULL DEFAULT 'OPEN',
  SU_ATTEMPTS       INT         NOT NULL DEFAULT 0,
  SU_RQ_UID_LAST    BIGINT      NULL,
  SU_SE_UID         BIGINT      NULL,
  SU_RESOLVED_ON    TIMESTAMPTZ NULL,
  SU_U_UID_RESOLVED BIGINT      NULL,
  SU_CREATED_BY     TEXT        NOT NULL,
  SU_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  SU_MODIFIED_BY    TEXT        NOT NULL,
  SU_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_SU_PF         FOREIGN KEY (SU_PF_UID)      REFERENCES PF_PROCESSED_FILE (PF_UID)  ON DELETE RESTRICT,
  CONSTRAINT FK_SU_CW         FOREIGN KEY (SU_CW_UID, SU_CW_KEY_HASH) REFERENCES CW_COLLATION_WINDOW (CW_UID, CW_KEY_HASH) ON DELETE RESTRICT,
  CONSTRAINT FK_SU_SRC        FOREIGN KEY (SU_SRC_UID)     REFERENCES SRC_SOURCE (SRC_UID)        ON DELETE RESTRICT,
  CONSTRAINT FK_SU_SE         FOREIGN KEY (SU_SE_UID)      REFERENCES SE_SUSPENSE_ESCROW (SE_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_SU_PLV        FOREIGN KEY (SU_PLV_UID)     REFERENCES PLV_PIPELINE_VERSION (PLV_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_SU_RQ_LAST    FOREIGN KEY (SU_RQ_UID_LAST) REFERENCES RQ_REPROCESS_REQUEST (RQ_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_SU_U_RESOLVED FOREIGN KEY (SU_U_UID_RESOLVED) REFERENCES U_USER (U_UID)            ON DELETE RESTRICT,
  CONSTRAINT CK_SU_ANCHOR  CHECK ((SU_PF_UID IS NOT NULL) <> (SU_CW_UID IS NOT NULL)),
  CONSTRAINT CK_SU_CW_HASH CHECK ((SU_CW_UID IS NULL) = (SU_CW_KEY_HASH IS NULL)),
  CONSTRAINT CK_SU_SCOPE   CHECK (SU_SCOPE IN ('RECORD','FILE','OUTPUT')),
  CONSTRAINT CK_SU_STAGE   CHECK (SU_STAGE IN ('COLLECT','DECODE','VALIDATE','DEDUP','COLLATE','ENRICH','TRANSFORM','DISTRIBUTE')),
  CONSTRAINT CK_SU_REASON_CLASS CHECK (SU_REASON_CLASS IN ('PERMANENT','TRANSIENT')),
  CONSTRAINT CK_SU_STATUS  CHECK (SU_STATUS IN ('OPEN','REPROCESSING','REPROCESSED','ABANDONED'))
);
CREATE INDEX IF NOT EXISTS IX_SU_SRC_STAGE_REASON ON SU_SUSPENSE (SU_SRC_UID, SU_STAGE, SU_REASON_CODE, SU_CREATED_ON);
CREATE INDEX IF NOT EXISTS IX_SU_STATUS_CREATED   ON SU_SUSPENSE (SU_STATUS, SU_CREATED_ON) WHERE SU_STATUS = 'OPEN';
CREATE INDEX IF NOT EXISTS IX_SU_PF_OPEN          ON SU_SUSPENSE (SU_PF_UID) WHERE SU_STATUS IN ('OPEN','REPROCESSING');

-- 3.5.9 AE_AUDIT_EVENT — append-only hash-chained audit trail (RANGE partitioned by chain time)
CREATE TABLE IF NOT EXISTS AE_AUDIT_EVENT (
  AE_UID              BIGINT GENERATED ALWAYS AS IDENTITY,
  AE_CHAIN_ON         TIMESTAMPTZ NOT NULL,
  AE_OCCURRED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  AE_SEQ              BIGINT      NOT NULL,
  AE_EVENT_TYPE       TEXT        NOT NULL,
  AE_CORRELATION_KIND TEXT        NOT NULL,
  AE_CORRELATION_ID   BIGINT      NULL,
  AE_ACTOR            TEXT        NOT NULL,
  AE_CONTEXT          JSONB       NULL,
  AE_PREV_HASH        BYTEA       NOT NULL,
  AE_HASH             BYTEA       NOT NULL,
  AE_CREATED_BY       TEXT        NOT NULL,
  AE_CREATED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  AE_MODIFIED_BY      TEXT        NOT NULL,
  AE_MODIFIED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT PK_AE PRIMARY KEY (AE_UID, AE_CHAIN_ON)
) PARTITION BY RANGE (AE_CHAIN_ON);
CREATE INDEX IF NOT EXISTS IX_AE_CORRELATION ON AE_AUDIT_EVENT (AE_CORRELATION_KIND, AE_CORRELATION_ID, AE_OCCURRED_ON);
CREATE INDEX IF NOT EXISTS IX_AE_TYPE_TIME   ON AE_AUDIT_EVENT (AE_EVENT_TYPE, AE_OCCURRED_ON);
CREATE INDEX IF NOT EXISTS IX_AE_SEQ         ON AE_AUDIT_EVENT (AE_SEQ);
-- default partition so appends work before the PARTITION_MAINTAIN job provisions monthly partitions
CREATE TABLE IF NOT EXISTS AE_AUDIT_EVENT_DEFAULT PARTITION OF AE_AUDIT_EVENT DEFAULT;

-- 3.8.1 AE append-only guard (idempotent)
CREATE OR REPLACE FUNCTION AE_APPEND_ONLY_GUARD() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'AE_AUDIT_EVENT is append-only (BR-AUD-004)';
END $$;
DROP TRIGGER IF EXISTS TG_AE_APPEND_ONLY ON AE_AUDIT_EVENT;
CREATE TRIGGER TG_AE_APPEND_ONLY BEFORE UPDATE OR DELETE ON AE_AUDIT_EVENT
  FOR EACH STATEMENT EXECUTE FUNCTION AE_APPEND_ONLY_GUARD();

-- 3.5.10 AA_AUDIT_ANCHOR — external chain anchors
CREATE TABLE IF NOT EXISTS AA_AUDIT_ANCHOR (
  AA_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AA_AE_SEQ      BIGINT      NOT NULL,
  AA_CHAIN_HASH  BYTEA       NOT NULL,
  AA_KIND        TEXT        NOT NULL DEFAULT 'PERIODIC',
  AA_EMITTED_TO  TEXT        NOT NULL,
  AA_EMITTED_ON  TIMESTAMPTZ NULL,
  AA_STATUS      TEXT        NOT NULL DEFAULT 'PENDING',
  AA_CREATED_BY  TEXT        NOT NULL,
  AA_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  AA_MODIFIED_BY TEXT        NOT NULL,
  AA_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT CK_AA_KIND   CHECK (AA_KIND IN ('PERIODIC','PRUNE_BOUNDARY')),
  CONSTRAINT CK_AA_STATUS CHECK (AA_STATUS IN ('PENDING','EMITTED','FAILED')),
  CONSTRAINT UX_AA_SEQ UNIQUE (AA_AE_SEQ, AA_EMITTED_TO)
);

-- 3.5.11 RS_RECONCILIATION_SUMMARY — conservation totals
CREATE TABLE IF NOT EXISTS RS_RECONCILIATION_SUMMARY (
  RS_UID                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RS_SCOPE                 TEXT        NOT NULL,
  RS_PF_UID                BIGINT      NULL,
  RS_SRC_UID               BIGINT      NULL,
  RS_PERIOD_START          TIMESTAMPTZ NULL,
  RS_PERIOD_END            TIMESTAMPTZ NULL,
  RS_BASELINE_KIND         TEXT        NOT NULL DEFAULT 'DECODED',
  RS_IN_COUNT              BIGINT      NOT NULL DEFAULT 0,
  RS_DECLARED_COUNT        BIGINT      NULL,
  RS_ROUTED_COUNT          BIGINT      NOT NULL DEFAULT 0,
  RS_DISCARDED_COUNT       BIGINT      NOT NULL DEFAULT 0,
  RS_SUSPENDED_COUNT       BIGINT      NOT NULL DEFAULT 0,
  RS_ABANDONED_COUNT       BIGINT      NOT NULL DEFAULT 0,
  RS_DUPLICATE_COUNT       BIGINT      NOT NULL DEFAULT 0,
  RS_AGGREGATED_COUNT      BIGINT      NOT NULL DEFAULT 0,
  RS_OPEN_COUNT            BIGINT      NOT NULL DEFAULT 0,
  RS_ADJ_EMITTED_COUNT     BIGINT      NOT NULL DEFAULT 0,
  RS_ADJ_CONTRIBUTED_COUNT BIGINT      NOT NULL DEFAULT 0,
  RS_QUARANTINED_COUNT     BIGINT      NOT NULL DEFAULT 0,
  RS_FILES_EXPECTED        BIGINT      NULL,
  RS_FILES_RECEIVED        BIGINT      NULL,
  RS_STATE                 TEXT        NOT NULL DEFAULT 'PENDING',
  RS_EXCEPTION             JSONB       NULL,
  RS_RULE_OUTCOMES         JSONB       NULL,
  RS_CREATED_BY            TEXT        NOT NULL,
  RS_CREATED_ON            TIMESTAMPTZ NOT NULL DEFAULT now(),
  RS_MODIFIED_BY           TEXT        NOT NULL,
  RS_MODIFIED_ON           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_RS_PF  FOREIGN KEY (RS_PF_UID)  REFERENCES PF_PROCESSED_FILE (PF_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_RS_SRC FOREIGN KEY (RS_SRC_UID) REFERENCES SRC_SOURCE (SRC_UID)       ON DELETE RESTRICT,
  CONSTRAINT CK_RS_SCOPE CHECK (RS_SCOPE IN ('FILE','STREAM','PERIOD')),
  CONSTRAINT CK_RS_BASELINE_KIND CHECK (RS_BASELINE_KIND IN ('TRAILER','DECODED','INDETERMINATE')),
  CONSTRAINT CK_RS_STATE CHECK (RS_STATE IN ('PENDING','BALANCED','EXCEPTION','INDETERMINATE'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_RS_FILE ON RS_RECONCILIATION_SUMMARY (RS_PF_UID) WHERE RS_SCOPE = 'FILE';
CREATE UNIQUE INDEX IF NOT EXISTS UX_RS_PERIOD ON RS_RECONCILIATION_SUMMARY (RS_SRC_UID, RS_SCOPE, RS_PERIOD_START) WHERE RS_SCOPE IN ('STREAM','PERIOD');
CREATE INDEX IF NOT EXISTS IX_RS_STATE ON RS_RECONCILIATION_SUMMARY (RS_STATE, RS_MODIFIED_ON) WHERE RS_STATE IN ('EXCEPTION','INDETERMINATE');

-- 3.5.12 DL_DELIVERY — delivery records
CREATE TABLE IF NOT EXISTS DL_DELIVERY (
  DL_UID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DL_DS_UID             BIGINT      NOT NULL,
  DL_PLV_UID            BIGINT      NOT NULL,
  DL_PF_UID             BIGINT      NULL,
  DL_CW_UID             BIGINT      NULL,
  DL_CW_KEY_HASH        BIGINT      NULL,
  DL_OUTPUT_IDENTITY    TEXT        NOT NULL,
  DL_IDENTITY_ADJUSTS   TEXT        NULL,
  DL_KIND               TEXT        NOT NULL DEFAULT 'ORIGINAL',
  DL_OUTPUT_NAME        TEXT        NULL,
  DL_SPOOL_PATH         TEXT        NULL,
  DL_OUTPUT_PATH        TEXT        NULL,
  DL_FORMAT             TEXT        NULL,
  DL_CHECKSUM           TEXT        NULL,
  DL_SEQUENCE_NO        BIGINT      NULL,
  DL_RECORD_COUNT       BIGINT      NULL,
  DL_SIZE_BYTES         BIGINT      NULL,
  DL_STATUS             TEXT        NOT NULL DEFAULT 'PENDING',
  DL_COMMITTED_THROUGH  BIGINT      NOT NULL DEFAULT 0,
  DL_DELIVERED_COUNT    BIGINT      NOT NULL DEFAULT 0,
  DL_ATTEMPTS           INT         NOT NULL DEFAULT 0,
  DL_NEXT_RETRY_ON      TIMESTAMPTZ NULL,
  DL_LAST_ERROR         TEXT        NULL,
  DL_INS_UID_LEASE      BIGINT      NULL,
  DL_LEASE_EXPIRES_ON   TIMESTAMPTZ NULL,
  DL_RESEND_COUNT       INT         NOT NULL DEFAULT 0,
  DL_WRITTEN_ON         TIMESTAMPTZ NULL,
  DL_DELIVERED_ON       TIMESTAMPTZ NULL,
  DL_OUTPUT_DISPOSITION TEXT        NOT NULL DEFAULT 'PRESENT',
  DL_CREATED_BY         TEXT        NOT NULL,
  DL_CREATED_ON         TIMESTAMPTZ NOT NULL DEFAULT now(),
  DL_MODIFIED_BY        TEXT        NOT NULL,
  DL_MODIFIED_ON        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_DL_DS  FOREIGN KEY (DL_DS_UID)  REFERENCES DS_DESTINATION (DS_UID)        ON DELETE RESTRICT,
  CONSTRAINT FK_DL_PLV FOREIGN KEY (DL_PLV_UID) REFERENCES PLV_PIPELINE_VERSION (PLV_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_DL_PF  FOREIGN KEY (DL_PF_UID)  REFERENCES PF_PROCESSED_FILE (PF_UID)     ON DELETE RESTRICT,
  CONSTRAINT FK_DL_INS_LEASE FOREIGN KEY (DL_INS_UID_LEASE) REFERENCES INS_INSTANCE (INS_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_DL_CW  FOREIGN KEY (DL_CW_UID, DL_CW_KEY_HASH) REFERENCES CW_COLLATION_WINDOW (CW_UID, CW_KEY_HASH) ON DELETE RESTRICT,
  CONSTRAINT CK_DL_KIND   CHECK (DL_KIND IN ('ORIGINAL','REPLAY','REPLACEMENT','DELTA')),
  CONSTRAINT CK_DL_STATUS CHECK (DL_STATUS IN
    ('PENDING','SPOOLED','PUBLISHING','WRITTEN','WRITTEN_UNCONFIRMED','DELIVERED','DIVERTED','FAILED')),
  CONSTRAINT CK_DL_OUTPUT_DISPOSITION CHECK (DL_OUTPUT_DISPOSITION IN ('PRESENT','CONSUMED','PRUNED','ARCHIVED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_DL_IDENTITY ON DL_DELIVERY (DL_DS_UID, DL_OUTPUT_IDENTITY) WHERE DL_KIND IN ('ORIGINAL','REPLACEMENT');
CREATE UNIQUE INDEX IF NOT EXISTS UX_DL_DS_SEQ ON DL_DELIVERY (DL_DS_UID, DL_SEQUENCE_NO) WHERE DL_SEQUENCE_NO IS NOT NULL;
CREATE INDEX IF NOT EXISTS IX_DL_RETRY ON DL_DELIVERY (DL_NEXT_RETRY_ON) WHERE DL_STATUS IN ('SPOOLED','PUBLISHING','WRITTEN_UNCONFIRMED');
CREATE INDEX IF NOT EXISTS IX_DL_PF ON DL_DELIVERY (DL_PF_UID, DL_STATUS);
CREATE INDEX IF NOT EXISTS IX_DL_DS_STATUS ON DL_DELIVERY (DL_DS_UID, DL_STATUS, DL_MODIFIED_ON);

-- 3.5.13 DSQ_DESTINATION_SEQUENCE — per-destination sequence allocator
CREATE TABLE IF NOT EXISTS DSQ_DESTINATION_SEQUENCE (
  DSQ_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DSQ_DS_UID      BIGINT      NOT NULL,
  DSQ_LAST_VALUE  BIGINT      NOT NULL DEFAULT 0,
  DSQ_CREATED_BY  TEXT        NOT NULL,
  DSQ_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  DSQ_MODIFIED_BY TEXT        NOT NULL,
  DSQ_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_DSQ_DS FOREIGN KEY (DSQ_DS_UID) REFERENCES DS_DESTINATION (DS_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_DSQ_DS UNIQUE (DSQ_DS_UID)
);

-- 3.5.15 AL_ALARM — alarms
CREATE TABLE IF NOT EXISTS AL_ALARM (
  AL_UID                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AL_TYPE                 TEXT        NOT NULL,
  AL_SEVERITY             TEXT        NOT NULL,
  AL_SOURCE_KIND          TEXT        NULL,
  AL_SOURCE_REF           BIGINT      NULL,   -- soft ref (no FK, §3.8.4)
  AL_MESSAGE              TEXT        NOT NULL,
  AL_CONTEXT              JSONB       NULL,
  AL_DEDUP_KEY            TEXT        NOT NULL,
  AL_STATUS               TEXT        NOT NULL DEFAULT 'OPEN',
  AL_RAISED_ON            TIMESTAMPTZ NOT NULL DEFAULT now(),
  AL_LAST_SEEN_ON         TIMESTAMPTZ NOT NULL DEFAULT now(),
  AL_OCCURRENCES          BIGINT      NOT NULL DEFAULT 1,
  AL_ACKNOWLEDGED_ON      TIMESTAMPTZ NULL,
  AL_U_UID_ACKNOWLEDGED   BIGINT      NULL,
  AL_RESOLVED_ON          TIMESTAMPTZ NULL,
  AL_U_UID_RESOLVED       BIGINT      NULL,
  AL_ESCALATION_LEVEL     INT         NOT NULL DEFAULT 0,
  AL_NEXT_ESCALATION_ON   TIMESTAMPTZ NULL,
  AL_AL_UID_SUPPRESSED_BY BIGINT      NULL,
  AL_CREATED_BY           TEXT        NOT NULL,
  AL_CREATED_ON           TIMESTAMPTZ NOT NULL DEFAULT now(),
  AL_MODIFIED_BY          TEXT        NOT NULL,
  AL_MODIFIED_ON          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_AL_U_ACKNOWLEDGED   FOREIGN KEY (AL_U_UID_ACKNOWLEDGED)   REFERENCES U_USER (U_UID)   ON DELETE RESTRICT,
  CONSTRAINT FK_AL_U_RESOLVED       FOREIGN KEY (AL_U_UID_RESOLVED)       REFERENCES U_USER (U_UID)   ON DELETE RESTRICT,
  CONSTRAINT FK_AL_AL_SUPPRESSED_BY FOREIGN KEY (AL_AL_UID_SUPPRESSED_BY) REFERENCES AL_ALARM (AL_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_AL_SEVERITY CHECK (AL_SEVERITY IN ('INFO','WARNING','MAJOR','CRITICAL')),
  CONSTRAINT CK_AL_STATUS   CHECK (AL_STATUS IN ('OPEN','ACKNOWLEDGED','SUPPRESSED','RESOLVED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_AL_DEDUP_OPEN ON AL_ALARM (AL_DEDUP_KEY) WHERE AL_STATUS IN ('OPEN','ACKNOWLEDGED','SUPPRESSED');
CREATE INDEX IF NOT EXISTS IX_AL_STATUS_SEVERITY ON AL_ALARM (AL_STATUS, AL_SEVERITY) WHERE AL_STATUS <> 'RESOLVED';
CREATE INDEX IF NOT EXISTS IX_AL_ESCALATION ON AL_ALARM (AL_NEXT_ESCALATION_ON) WHERE AL_STATUS = 'OPEN';

-- 3.5.16 AN_ALARM_NOTIFICATION — notification sends + callback tokens
CREATE TABLE IF NOT EXISTS AN_ALARM_NOTIFICATION (
  AN_UID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AN_AL_UID           BIGINT      NOT NULL,
  AN_CHANNEL          TEXT        NOT NULL DEFAULT 'EMAIL',
  AN_RECIPIENT        TEXT        NOT NULL,
  AN_SENT_ON          TIMESTAMPTZ NULL,
  AN_STATUS           TEXT        NOT NULL DEFAULT 'QUEUED',
  AN_ESCALATION_LEVEL INT         NOT NULL DEFAULT 0,
  AN_ACTION           TEXT        NULL,
  AN_TOKEN_HASH       BYTEA       NULL,
  AN_TOKEN_EXPIRES_ON TIMESTAMPTZ NULL,
  AN_TOKEN_USED_ON    TIMESTAMPTZ NULL,
  AN_CREATED_BY       TEXT        NOT NULL,
  AN_CREATED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  AN_MODIFIED_BY      TEXT        NOT NULL,
  AN_MODIFIED_ON      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_AN_AL FOREIGN KEY (AN_AL_UID) REFERENCES AL_ALARM (AL_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_AN_TOKEN UNIQUE (AN_TOKEN_HASH),
  CONSTRAINT CK_AN_STATUS CHECK (AN_STATUS IN ('QUEUED','SENT','FAILED')),
  CONSTRAINT CK_AN_ACTION CHECK (AN_ACTION IS NULL OR AN_ACTION IN ('ACK','RESOLVE'))
);
CREATE INDEX IF NOT EXISTS IX_AN_AL ON AN_ALARM_NOTIFICATION (AN_AL_UID);

-- 3.5.17 AR_ARCHIVE_RUN — archive run outcomes
CREATE TABLE IF NOT EXISTS AR_ARCHIVE_RUN (
  AR_UID          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  AR_AP_UID       BIGINT      NOT NULL,
  AR_STARTED_ON   TIMESTAMPTZ NOT NULL DEFAULT now(),
  AR_FINISHED_ON  TIMESTAMPTZ NULL,
  AR_ARCHIVE_NAME TEXT        NULL,
  AR_SIZE_BYTES   BIGINT      NULL,
  AR_CHECKSUM     TEXT        NULL,
  AR_TARGET       TEXT        NULL,
  AR_FILE_COUNT   INT         NOT NULL DEFAULT 0,
  AR_STATUS       TEXT        NOT NULL DEFAULT 'SELECTING',
  AR_ERROR        TEXT        NULL,
  AR_CREATED_BY   TEXT        NOT NULL,
  AR_CREATED_ON   TIMESTAMPTZ NOT NULL DEFAULT now(),
  AR_MODIFIED_BY  TEXT        NOT NULL,
  AR_MODIFIED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_AR_AP FOREIGN KEY (AR_AP_UID) REFERENCES AP_ARCHIVE_POLICY (AP_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_AR_STATUS CHECK (AR_STATUS IN
    ('SELECTING','COMPRESSING','UPLOADING','VERIFYING','PRUNING','COMPLETE','FAILED'))
);

-- 3.5.17 ARF_ARCHIVE_RUN_FILE — files in an archive run
CREATE TABLE IF NOT EXISTS ARF_ARCHIVE_RUN_FILE (
  ARF_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ARF_AR_UID      BIGINT      NOT NULL,
  ARF_PF_UID      BIGINT      NOT NULL,
  ARF_PRUNED      BOOLEAN     NOT NULL DEFAULT FALSE,
  ARF_CREATED_BY  TEXT        NOT NULL,
  ARF_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  ARF_MODIFIED_BY TEXT        NOT NULL,
  ARF_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_ARF_AR FOREIGN KEY (ARF_AR_UID) REFERENCES AR_ARCHIVE_RUN (AR_UID)    ON DELETE RESTRICT,
  CONSTRAINT FK_ARF_PF FOREIGN KEY (ARF_PF_UID) REFERENCES PF_PROCESSED_FILE (PF_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_ARF_AR_PF UNIQUE (ARF_AR_UID, ARF_PF_UID)
);
CREATE INDEX IF NOT EXISTS IX_ARF_PF ON ARF_ARCHIVE_RUN_FILE (ARF_PF_UID);

-- 3.5.19 SJ_SCHEDULED_JOB — scheduled/singleton jobs
CREATE TABLE IF NOT EXISTS SJ_SCHEDULED_JOB (
  SJ_UID               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SJ_KIND              TEXT        NOT NULL,
  SJ_SCOPE             TEXT        NOT NULL DEFAULT '',
  SJ_SCHEDULE          TEXT        NOT NULL,
  SJ_ENABLED           BOOLEAN     NOT NULL DEFAULT TRUE,
  SJ_INS_UID_NOMINATED BIGINT      NULL,
  SJ_INS_UID_LEASE     BIGINT      NULL,
  SJ_LEASE_ACQUIRED_ON TIMESTAMPTZ NULL,
  SJ_LEASE_EXPIRES_ON  TIMESTAMPTZ NULL,
  SJ_FENCE             BIGINT      NOT NULL DEFAULT 0,
  SJ_LAST_RUN_ON       TIMESTAMPTZ NULL,
  SJ_LAST_OUTCOME      TEXT        NULL,
  SJ_CREATED_BY        TEXT        NOT NULL,
  SJ_CREATED_ON        TIMESTAMPTZ NOT NULL DEFAULT now(),
  SJ_MODIFIED_BY       TEXT        NOT NULL,
  SJ_MODIFIED_ON       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_SJ_INS_NOMINATED FOREIGN KEY (SJ_INS_UID_NOMINATED) REFERENCES INS_INSTANCE (INS_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_SJ_INS_LEASE     FOREIGN KEY (SJ_INS_UID_LEASE)     REFERENCES INS_INSTANCE (INS_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_SJ_KIND_SCOPE UNIQUE (SJ_KIND, SJ_SCOPE),
  CONSTRAINT CK_SJ_KIND CHECK (SJ_KIND IN
    ('FETCH','ARCHIVE','LIVENESS','PARTITION_MAINTAIN','RETENTION_PRUNE','ALARM_ESCALATE',
     'RECON_ROLLUP','AUDIT_ANCHOR','SESSION_SWEEP','DISK_PRESSURE','DB_DISK_RECONCILE'))
);

-- 3.5.23 DC_DELIVERY_CONTRIBUTION — output <-> source-file fan-in
CREATE TABLE IF NOT EXISTS DC_DELIVERY_CONTRIBUTION (
  DC_UID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DC_DL_UID             BIGINT      NOT NULL,
  DC_PF_UID             BIGINT      NOT NULL,
  DC_RECORD_COUNT       BIGINT      NOT NULL DEFAULT 0,
  DC_FIRST_RECORD_INDEX BIGINT      NULL,
  DC_LAST_RECORD_INDEX  BIGINT      NULL,
  DC_CREATED_BY         TEXT        NOT NULL,
  DC_CREATED_ON         TIMESTAMPTZ NOT NULL DEFAULT now(),
  DC_MODIFIED_BY        TEXT        NOT NULL,
  DC_MODIFIED_ON        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_DC_DL FOREIGN KEY (DC_DL_UID) REFERENCES DL_DELIVERY (DL_UID)       ON DELETE RESTRICT,
  CONSTRAINT FK_DC_PF FOREIGN KEY (DC_PF_UID) REFERENCES PF_PROCESSED_FILE (PF_UID) ON DELETE RESTRICT,
  CONSTRAINT UX_DC_DL_PF UNIQUE (DC_DL_UID, DC_PF_UID)
);
CREATE INDEX IF NOT EXISTS IX_DC_PF ON DC_DELIVERY_CONTRIBUTION (DC_PF_UID);

-- 3.5.21b BT_BATCH / BF_BATCH_FILE — output consolidation (TS 07 §7.3.2, BR-DST-005)
--
-- A batch is a FROZEN set of input files that together produce ONE output object
-- per destination. It has to be durable, and it has to be frozen, for one reason:
-- destinations deliver INDEPENDENTLY (a Revenue Assurance outage must not stall
-- the Billing feed). The moment one destination has published, the membership can
-- no longer change — a retry that re-formed the batch with an extra file would
-- re-deliver the already-published records to that destination as duplicates.
--
-- So: membership is pinned here at formation; each destination's delivery is
-- tracked in its own DL_DELIVERY row keyed (DL_DS_UID, DL_OUTPUT_IDENTITY =
-- BT_IDENTITY); a retry re-delivers ONLY to destinations without a DELIVERED row.
-- The DL row also RESERVES the destination sequence number, so a retry reuses its
-- number instead of burning a new one — a gap in the delivered sequence therefore
-- means a genuinely missing output (BR-DST-011), never a failed attempt.
--
-- The contributing files reach DONE (PF rows + DC contributions) only when EVERY
-- destination has delivered (BR-COL-009); until then the batch stays OPEN and its
-- files are excluded from any new batch.
CREATE TABLE IF NOT EXISTS BT_BATCH (
  BT_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BT_PL_UID      BIGINT      NOT NULL,
  BT_SRC_UID     BIGINT      NOT NULL,
  BT_PLV_UID     BIGINT      NOT NULL,
  BT_IDENTITY    TEXT        NOT NULL,   -- deterministic hash of the member set
  BT_STATUS      TEXT        NOT NULL DEFAULT 'OPEN',
  BT_FILE_COUNT  INT         NOT NULL,
  BT_SIZE_BYTES  BIGINT      NOT NULL DEFAULT 0,
  BT_ATTEMPTS    INT         NOT NULL DEFAULT 0,
  BT_LAST_ERROR  TEXT        NULL,
  BT_CREATED_BY  TEXT        NOT NULL,
  BT_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  BT_MODIFIED_BY TEXT        NOT NULL,
  BT_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_BT_PL  FOREIGN KEY (BT_PL_UID)  REFERENCES PL_PIPELINE (PL_UID)          ON DELETE RESTRICT,
  CONSTRAINT FK_BT_SRC FOREIGN KEY (BT_SRC_UID) REFERENCES SRC_SOURCE (SRC_UID)          ON DELETE RESTRICT,
  CONSTRAINT FK_BT_PLV FOREIGN KEY (BT_PLV_UID) REFERENCES PLV_PIPELINE_VERSION (PLV_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_BT_STATUS CHECK (BT_STATUS IN ('OPEN','CLOSED','ABANDONED'))
);
-- One live batch per identity per source: two instances racing to form the same
-- batch collide here, and the loser resumes the winner's batch instead.
CREATE UNIQUE INDEX IF NOT EXISTS UX_BT_SRC_IDENTITY_OPEN ON BT_BATCH (BT_SRC_UID, BT_IDENTITY) WHERE BT_STATUS = 'OPEN';
CREATE INDEX IF NOT EXISTS IX_BT_OPEN ON BT_BATCH (BT_SRC_UID) WHERE BT_STATUS = 'OPEN';

CREATE TABLE IF NOT EXISTS BF_BATCH_FILE (
  BF_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BF_BT_UID      BIGINT      NOT NULL,
  BF_NAME        TEXT        NOT NULL,
  BF_SIZE_BYTES  BIGINT      NOT NULL DEFAULT 0,
  BF_SEQ         INT         NOT NULL,   -- position within the batch (stable order)
  -- Per-file record counts, written once the batch has been encoded. They exist so
  -- that a batch which crashed AFTER delivering but BEFORE committing can still
  -- write truthful PF rows on resume (in = out + suspended, BR-REC-001) rather than
  -- recording the files as DONE with zero records.
  BF_RECORDS_IN  BIGINT      NOT NULL DEFAULT 0,
  BF_RECORDS_OUT BIGINT      NOT NULL DEFAULT 0,
  BF_SUSPENDED   BIGINT      NOT NULL DEFAULT 0,
  BF_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_BF_BT FOREIGN KEY (BF_BT_UID) REFERENCES BT_BATCH (BT_UID) ON DELETE CASCADE,
  CONSTRAINT UX_BF_BT_NAME UNIQUE (BF_BT_UID, BF_NAME)
);
CREATE INDEX IF NOT EXISTS IX_BF_NAME ON BF_BATCH_FILE (BF_NAME);
ALTER TABLE BF_BATCH_FILE ADD COLUMN IF NOT EXISTS BF_RECORDS_IN  BIGINT NOT NULL DEFAULT 0;
ALTER TABLE BF_BATCH_FILE ADD COLUMN IF NOT EXISTS BF_RECORDS_OUT BIGINT NOT NULL DEFAULT 0;
ALTER TABLE BF_BATCH_FILE ADD COLUMN IF NOT EXISTS BF_SUSPENDED   BIGINT NOT NULL DEFAULT 0;

-- 3.5.22 OS_OPERATIONAL_STATE — declared operational states
CREATE TABLE IF NOT EXISTS OS_OPERATIONAL_STATE (
  OS_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  OS_KIND           TEXT        NOT NULL,
  OS_SCOPE          TEXT        NOT NULL,
  OS_SRC_UID        BIGINT      NULL,
  OS_PL_UID         BIGINT      NULL,
  OS_DS_UID         BIGINT      NULL,
  OS_INS_UID        BIGINT      NULL,
  OS_STATUS         TEXT        NOT NULL DEFAULT 'ACTIVE',
  OS_STARTED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  OS_CLEARED_ON     TIMESTAMPTZ NULL,
  OS_REASON         TEXT        NULL,
  OS_U_UID_DECLARED BIGINT      NULL,
  OS_AL_UID         BIGINT      NULL,
  OS_CREATED_BY     TEXT        NOT NULL,
  OS_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  OS_MODIFIED_BY    TEXT        NOT NULL,
  OS_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_OS_SRC        FOREIGN KEY (OS_SRC_UID)        REFERENCES SRC_SOURCE (SRC_UID)    ON DELETE RESTRICT,
  CONSTRAINT FK_OS_PL         FOREIGN KEY (OS_PL_UID)         REFERENCES PL_PIPELINE (PL_UID)    ON DELETE RESTRICT,
  CONSTRAINT FK_OS_DS         FOREIGN KEY (OS_DS_UID)         REFERENCES DS_DESTINATION (DS_UID) ON DELETE RESTRICT,
  CONSTRAINT FK_OS_INS        FOREIGN KEY (OS_INS_UID)        REFERENCES INS_INSTANCE (INS_UID)  ON DELETE RESTRICT,
  CONSTRAINT FK_OS_U_DECLARED FOREIGN KEY (OS_U_UID_DECLARED) REFERENCES U_USER (U_UID)          ON DELETE RESTRICT,
  CONSTRAINT FK_OS_AL         FOREIGN KEY (OS_AL_UID)         REFERENCES AL_ALARM (AL_UID)       ON DELETE RESTRICT,
  CONSTRAINT CK_OS_KIND CHECK (OS_KIND IN
    ('PAUSE','STOP','PAUSE_INTAKE_OVERFLOW','FETCH_PAUSE','STAGING_QUOTA','READINESS_HOLD','FAIL_CLOSED','CATCHUP')),
  CONSTRAINT CK_OS_SCOPE CHECK (OS_SCOPE IN ('SOURCE','PIPELINE','DESTINATION','INSTANCE','CLUSTER')),
  CONSTRAINT CK_OS_STATUS CHECK (OS_STATUS IN ('ACTIVE','CLEARED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_OS_ACTIVE ON OS_OPERATIONAL_STATE
  (OS_KIND, OS_SCOPE, OS_SRC_UID, OS_PL_UID, OS_DS_UID, OS_INS_UID)
  NULLS NOT DISTINCT WHERE OS_STATUS = 'ACTIVE';
CREATE INDEX IF NOT EXISTS IX_OS_ACTIVE_SCOPE ON OS_OPERATIONAL_STATE (OS_SRC_UID, OS_PL_UID) WHERE OS_STATUS = 'ACTIVE';

-- 3.5.25 RTN_RETENTION_POLICY — per-store retention + lawful basis
CREATE TABLE IF NOT EXISTS RTN_RETENTION_POLICY (
  RTN_UID            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RTN_RTN_UID_ROOT   BIGINT      NULL,
  RTN_VERSION_NO     INT         NOT NULL,
  RTN_STATUS         TEXT        NOT NULL DEFAULT 'DRAFT',
  RTN_EFFECTIVE_FROM TIMESTAMPTZ NOT NULL,
  RTN_END_DATE       TIMESTAMPTZ NULL,
  RTN_STORE          TEXT        NOT NULL,
  RTN_SCOPE          TEXT        NULL,
  RTN_PERIOD         INTERVAL    NULL,
  RTN_LAWFUL_BASIS   TEXT        NULL,
  RTN_CREATED_BY     TEXT        NOT NULL,
  RTN_CREATED_ON     TIMESTAMPTZ NOT NULL DEFAULT now(),
  RTN_MODIFIED_BY    TEXT        NOT NULL,
  RTN_MODIFIED_ON    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT FK_RTN_RTN_ROOT FOREIGN KEY (RTN_RTN_UID_ROOT) REFERENCES RTN_RETENTION_POLICY (RTN_UID) ON DELETE RESTRICT,
  CONSTRAINT CK_RTN_STATUS CHECK (RTN_STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_RTN_ROOT_VERSION ON RTN_RETENTION_POLICY (COALESCE(RTN_RTN_UID_ROOT, RTN_UID), RTN_VERSION_NO);
CREATE INDEX IF NOT EXISTS IX_RTN_ROOT_EFFECTIVE ON RTN_RETENTION_POLICY (COALESCE(RTN_RTN_UID_ROOT, RTN_UID), RTN_EFFECTIVE_FROM) WHERE RTN_STATUS = 'PUBLISHED';
CREATE UNIQUE INDEX IF NOT EXISTS UX_RTN_STORE_SCOPE_OPEN ON RTN_RETENTION_POLICY (RTN_STORE, COALESCE(RTN_SCOPE,'')) WHERE RTN_STATUS = 'PUBLISHED' AND RTN_END_DATE IS NULL;

-- =============================================================================
-- SEED DATA  (all guarded ON CONFLICT DO NOTHING — safe to re-run)
-- =============================================================================

-- Named transactional counters (§2.5, §3.5.14, §3.8.2):
--   FILE_UID   — business file-UID counter (starts at 0)
--   AUDIT_CHAIN — hash-chain head + monotonic chain-time high-water (genesis = 32 zero bytes)
INSERT INTO SQ_SEQUENCE_ALLOCATOR (SQ_NAME, SQ_LAST_VALUE, SQ_CREATED_BY, SQ_MODIFIED_BY)
VALUES ('FILE_UID', 0, 'engine:bootstrap', 'engine:bootstrap')
ON CONFLICT (SQ_NAME) DO NOTHING;

INSERT INTO SQ_SEQUENCE_ALLOCATOR (SQ_NAME, SQ_LAST_VALUE, SQ_CHAIN_HASH, SQ_CHAIN_ON, SQ_CREATED_BY, SQ_MODIFIED_BY)
VALUES ('AUDIT_CHAIN', 0,
        '\x0000000000000000000000000000000000000000000000000000000000000000'::bytea,
        now(), 'engine:bootstrap', 'engine:bootstrap')
ON CONFLICT (SQ_NAME) DO NOTHING;

-- Four built-in roles (§3.3.2; not deletable — R_BUILT_IN = TRUE)
INSERT INTO R_ROLE (R_NAME, R_DESCRIPTION, R_BUILT_IN, R_CREATED_BY, R_MODIFIED_BY) VALUES
  ('Administrator', 'Full administrative control of users, config, and operations', TRUE, 'engine:bootstrap', 'engine:bootstrap'),
  ('Configurer',    'Create/edit/publish configuration',                            TRUE, 'engine:bootstrap', 'engine:bootstrap'),
  ('Operator',      'Operate the running engine: pause/resume, reprocess, acknowledge alarms', TRUE, 'engine:bootstrap', 'engine:bootstrap'),
  ('Viewer',        'Read-only visibility of configuration and operations',         TRUE, 'engine:bootstrap', 'engine:bootstrap')
ON CONFLICT (R_NAME) DO NOTHING;

-- Bootstrap admin user (§3.3.1, BR-USR-009). The U_PASSWORD_HASH below is an INERT
-- PLACEHOLDER, not a valid argon2id hash — no password verifies against it. The app
-- forces a reset on first run (U_MUST_CHANGE_PASSWORD = TRUE). Replace via first-run flow.
INSERT INTO U_USER (U_USERNAME, U_DISPLAY_NAME, U_AUTH_SOURCE, U_PASSWORD_HASH,
                    U_STATUS, U_MUST_CHANGE_PASSWORD, U_CREATED_BY, U_MODIFIED_BY)
VALUES ('admin', 'Bootstrap Administrator', 'LOCAL',
        'PLACEHOLDER:reset-on-first-run',  -- NOT a real hash; app resets it
        'ACTIVE', TRUE, 'engine:bootstrap', 'engine:bootstrap')
ON CONFLICT (U_USERNAME) DO NOTHING;

-- Grant the bootstrap admin the Administrator role
INSERT INTO UR_USER_ROLE (UR_U_UID, UR_R_UID, UR_CREATED_BY, UR_MODIFIED_BY)
SELECT u.U_UID, r.R_UID, 'engine:bootstrap', 'engine:bootstrap'
FROM U_USER u, R_ROLE r
WHERE u.U_USERNAME = 'admin' AND r.R_NAME = 'Administrator'
ON CONFLICT (UR_U_UID, UR_R_UID) DO NOTHING;

-- Baseline migration ledger row (§3.5.21)
INSERT INTO SM_SCHEMA_MIGRATION (SM_VERSION, SM_CHECKSUM, SM_STATUS, SM_CREATED_BY, SM_MODIFIED_BY)
VALUES ('0001_initial', 'baseline', 'APPLIED', 'engine:bootstrap', 'engine:bootstrap')
ON CONFLICT (SM_VERSION) DO NOTHING;

-- =============================================================================
-- 3.4.9  DSR_DATASOURCE — reusable storage connections (posix/s3) that pipelines
--        select as their input and/or output location (cloud-native track).
--        Additive to the 0001 baseline; no other table FKs into it — pipelines
--        link it by id inside the PLV_STAGE_GRAPH JSONB document. Connection
--        config (incl. the encrypted S3 secret key) lives in DSR_CONFIG, mirroring
--        the SRC/PLV encrypted-JSONB pattern.
-- =============================================================================
CREATE TABLE IF NOT EXISTS DSR_DATASOURCE (
  DSR_UID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DSR_NAME        TEXT        NOT NULL,
  DSR_KIND        TEXT        NOT NULL,
  DSR_CONFIG      JSONB       NOT NULL,
  DSR_STATUS      TEXT        NOT NULL DEFAULT 'ACTIVE',
  DSR_CREATED_BY  TEXT        NOT NULL,
  DSR_CREATED_ON  TIMESTAMPTZ NOT NULL DEFAULT now(),
  DSR_MODIFIED_BY TEXT        NOT NULL,
  DSR_MODIFIED_ON TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT CK_DSR_KIND   CHECK (DSR_KIND IN ('posix','s3')),
  CONSTRAINT CK_DSR_STATUS CHECK (DSR_STATUS IN ('ACTIVE','DISABLED'))
);
-- Name is unique among ACTIVE datasources; a soft-delete sets DISABLED so any
-- pipeline still referencing the datasource by id resolves (config is data,
-- never destroyed — TS ground rule §6).
CREATE UNIQUE INDEX IF NOT EXISTS UX_DSR_NAME_ACTIVE ON DSR_DATASOURCE (DSR_NAME) WHERE DSR_STATUS = 'ACTIVE';

-- PF_PROCESSED_FILE: carry a reason for QUARANTINED / errored files so the GUI can
-- show WHY a file failed. Added via idempotent ALTER because CREATE TABLE IF NOT
-- EXISTS above does not backfill columns onto an already-provisioned table.
ALTER TABLE PF_PROCESSED_FILE ADD COLUMN IF NOT EXISTS PF_REASON_CODE TEXT NULL;
ALTER TABLE PF_PROCESSED_FILE ADD COLUMN IF NOT EXISTS PF_ERROR_TEXT  TEXT NULL;

-- =============================================================================
-- End of baasparse baseline schema (0001_initial)
-- =============================================================================
